import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {assertUploadMutation,buildVersionMetadata,deterministicIdentity,EXPECTED_ACTIVE_VERSION_ID,EXPECTED_COMPATIBILITY_DATE,EXPECTED_CRON,EXPECTED_SEASON,MODULE_PATHS,parseAndValidateConfig,validateModuleGraph,WORKER_NAME} from '../workers/data-platform/phase4b/upload-version.mjs';
import {parseAndValidateConfig as phase2Config} from '../workers/data-platform/phase2/upload-version.mjs';
const config=fs.readFileSync('workers/data-platform/wrangler.jsonc','utf8');const helper=fs.readFileSync('workers/data-platform/phase4b/upload-version.mjs','utf8');const workflow=fs.readFileSync('.github/workflows/data-s2b-phase4b-version-upload.yml','utf8');
test('Phase 4B accepts exact candidate config while frozen Phase 2 rejects it',()=>{assert.equal(parseAndValidateConfig(config).triggers.crons[0],EXPECTED_CRON);assert.throws(()=>phase2Config(config),/phase2_triggers_drift/);});
test('identity, compatibility, season and module allowlist are exact',()=>{assert.equal(WORKER_NAME,'teamsheet-data-platform');assert.equal(EXPECTED_ACTIVE_VERSION_ID,'3a2b065a-6527-4887-9bf8-b08e82e81133');assert.equal(EXPECTED_COMPATIBILITY_DATE,'2026-08-22');assert.equal(EXPECTED_SEASON,'2026-27');assert.deepEqual(MODULE_PATHS.map(x=>x.split('/').at(-1)),['data-platform-rpc.mjs','data-platform.mjs','data-platform-core.mjs','official-fpl-history.mjs']);validateModuleGraph();});
test('module and metadata hashes are deterministic',()=>{const sources=validateModuleGraph(),meta=buildVersionMetadata(EXPECTED_ACTIVE_VERSION_ID,'a'.repeat(40));assert.deepEqual(deterministicIdentity(meta,sources),deterministicIdentity(meta,sources));assert.match(deterministicIdentity(meta,sources).metadata_sha256,/^[a-f0-9]{64}$/);});
test('metadata pins inherited D1 and retained secret to the exact active Version without serialising a secret value',()=>{const value=buildVersionMetadata(EXPECTED_ACTIVE_VERSION_ID,'a'.repeat(40));assert.deepEqual(value.bindings,[{name:'TEAMSHEET_DATA_DB',type:'inherit',version_id:EXPECTED_ACTIVE_VERSION_ID},{name:'DATA_S1_HTTP_AUTH_TOKEN',type:'inherit',version_id:EXPECTED_ACTIVE_VERSION_ID},{name:'DATA_S2_SEASON',type:'plain_text',text:'2026-27'}]);assert.equal(JSON.stringify(value).includes('secret_text'),false);});
test('upload mutation allowlist permits only the exact versions POST',()=>{const base='/accounts/a/workers/scripts/teamsheet-data-platform';assert.equal(assertUploadMutation('POST',`${base}/versions?bindings_inherit=strict`,base),true);for(const path of [`${base}/deployments`,`${base}/schedules`,`${base}`,`${base}/secrets`,`/accounts/a/workers/domains`,`/accounts/a/access/apps`,`/accounts/a/d1/database/x/query`])assert.throws(()=>assertUploadMutation('POST',path,base),/mutation_endpoint_forbidden/);});
test('upload is one-shot and ambiguity is reconciled without retry',()=>{assert.match(helper,/phase4b_upload_response_ambiguous/);assert.match(helper,/reconcil/);assert.doesNotMatch(helper,/wrangler\s+(?:deploy|triggers)/);assert.doesNotMatch(helper,/\/schedules[^`'"\n]*[\s\S]{0,80}method:\s*'POST'/);});
test('Cron and D1 are immutable pre/post invariants',()=>{assert.match(helper,/assessCron\(schedulesBefore\)/);assert.match(helper,/assessCron\(schedulesAfter\)/);assert.match(helper,/phase4b_d1_size_changed/);assert.match(helper,/validatePostPhase1State\(await readPhase1State\(\)\)/);});
test('manual workflow gates identity and CI before protected credentials',()=>{
  for(const expected of [/workflow_dispatch:/,/approved_sha:/,/refs\/heads\/main/,/priteshpatel390-del\/FPL/,/\^\[0-9a-f\]\{40\}\$/,/ref: \$\{\{ inputs\.approved_sha \}\}/,/ref: \$\{\{ needs\.repository-gate\.outputs\.approved_sha \}\}/,/git ls-remote/,/git status --porcelain/,/Tests and deterministic build/,/environment:\s*\n\s+name: data-s2b-phase3-deployment/,/node-version: 24\.19\.0/,/needs: repository-gate/])assert.match(workflow,expected);
  assert.doesNotMatch(workflow,/^\s{2}(?:push|schedule|pull_request|pull_request_target|workflow_run|repository_dispatch|issue_comment):/m);
  for(const credential of ['CLOUDFLARE_WORKER_UPLOAD_TOKEN','CLOUDFLARE_PHASE3_DEPLOY_TOKEN','CLOUDFLARE_ACCOUNT_ID','DATA_S1_HTTP_AUTH_TOKEN','CF_ACCESS_CLIENT_ID','CF_ACCESS_CLIENT_SECRET','data-s2b-phase3-deployment'])assert.ok(workflow.indexOf('repository-gate:')<workflow.indexOf(credential));
});
test('workflow maps the proven Phase 3 protected environment credentials exactly',()=>{
  assert.match(workflow,/CLOUDFLARE_WORKER_UPLOAD_TOKEN: \$\{\{ secrets\.CLOUDFLARE_PHASE3_DEPLOY_TOKEN \}\}/);
  for(const retained of [/CLOUDFLARE_ACCOUNT_ID: \$\{\{ secrets\.CLOUDFLARE_ACCOUNT_ID \}\}/,/DATA_S1_HTTP_AUTH_TOKEN: \$\{\{ secrets\.DATA_S1_HTTP_AUTH_TOKEN \}\}/,/CF_ACCESS_CLIENT_ID: \$\{\{ secrets\.CF_ACCESS_CLIENT_ID \}\}/,/CF_ACCESS_CLIENT_SECRET: \$\{\{ secrets\.CF_ACCESS_CLIENT_SECRET \}\}/])assert.match(workflow,retained);
  assert.deepEqual([...new Set([...workflow.matchAll(/secrets\.([A-Z0-9_]+)/g)].map(row=>row[1]))].sort(),['CF_ACCESS_CLIENT_ID','CF_ACCESS_CLIENT_SECRET','CLOUDFLARE_ACCOUNT_ID','CLOUDFLARE_PHASE3_DEPLOY_TOKEN','DATA_S1_HTTP_AUTH_TOKEN']);
  assert.doesNotMatch(workflow,/secrets\.CLOUDFLARE_WORKER_UPLOAD_TOKEN|secrets\.CLOUDFLARE_API_TOKEN|CLOUDFLARE_D1_WRITE_TOKEN|data-s2b-phase(?:0-readonly|1-migration|2-version-upload)/);
});
test('workflow invokes only the standalone upload executable and no deployment, preflight, migration or collector path',()=>{
  assert.deepEqual([...workflow.matchAll(/node\s+(\S+\.mjs)/g)].map(row=>row[1]),['workers/data-platform/phase4b/upload-version.mjs']);
  assert.doesNotMatch(workflow,/deploy-version\.mjs|preflight\.mjs|deploy-candidate\.mjs|migrate-0002\.mjs|readonly-closeout\.mjs|collector\.mjs|wrangler\s+(?:deploy|triggers(?:\s+deploy)?)/);
});
