import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createD1RestClient,D1RestError,D1_REST_REQUEST_LIMIT_BYTES} from '../workers/data-platform/d1-rest-client.mjs';
import {buildRunRead,buildStartRunMutation,buildCommitBatch} from '../workers/data-platform/official-fpl-d1-rest-plan.mjs';
const config={accountId:'account_123',databaseId:'db-456',token:'super-secret'};
const ok=count=>({status:200,json:async()=>({success:true,result:Array.from({length:count},()=>({success:true,results:[],meta:{}}))})});
const read=()=>buildRunRead({runId:'run-1',sourceRevisionId:'official-fpl-r1'});
const capture=()=>{const calls=[];return {calls,client:createD1RestClient({...config,transport:async request=>(calls.push(request),ok(1))})};};
const code=expected=>error=>error instanceof D1RestError&&error.code===expected;

test('fixed Cloudflare URL, POST, redirect rejection and exact single-query shape',async()=>{const {calls,client}=capture();await client.run(read());assert.equal(calls.length,1);assert.deepEqual({...calls[0],headers:{...calls[0].headers}},{method:'POST',url:'https://api.cloudflare.com/client/v4/accounts/account_123/d1/database/db-456/query',headers:{Authorization:'Bearer super-secret','Content-Type':'application/json'},body:JSON.stringify(read().statements[0]),redirect:'error'});});
test('configuration rejects arbitrary host, URL, base URL, absent transport and unsafe identifiers',()=>{for(const extra of [{host:'evil.test'},{url:'https://evil.test'},{baseUrl:'https://evil.test'}])assert.throws(()=>createD1RestClient({...config,transport:async()=>ok(1),...extra}),code('d1_config_invalid'));for(const value of ['https://evil.test','a/b',''])assert.throws(()=>createD1RestClient({...config,accountId:value,transport:async()=>ok(1)}),code('d1_config_invalid'));assert.throws(()=>createD1RestClient(config),code('d1_config_invalid'));});
test('raw SQL, forged, unknown and tampered plans are rejected before transport',async()=>{let calls=0;const client=createD1RestClient({...config,transport:async()=>{calls++;return ok(1);}});for(const plan of [{sql:'SELECT 1',params:[]},{kind:'read',mutation:false,statements:[{sql:'SELECT 1',params:[]}]},Object.freeze({})])await assert.rejects(client.run(plan),code('d1_plan_untrusted'));const plan=read();assert.throws(()=>plan.statements[0].params.push('x'));await client.run(plan);assert.equal(calls,1);});
test('batch body uses Cloudflare batch wrapper and preserves statement and string parameter ordering deterministically',async()=>{const requests=[];const client=createD1RestClient({...config,transport:async request=>(requests.push(request),ok(3))});const input={entities:[],previousRows:[],observations:[{logical_key:'b',observation_id:'2'},{logical_key:'a',observation_id:'1'}],completedAt:'2026-09-01T02:00:00.000Z',recordsSeen:2,runId:'run',sourceRevisionId:'official-fpl-r1'};await client.run(buildCommitBatch(input));await client.run(buildCommitBatch(input));assert.equal(requests[0].body,requests[1].body);const body=JSON.parse(requests[0].body);assert.ok(Array.isArray(body.batch));assert.deepEqual(JSON.parse(body.batch[0].params[0]).map(row=>row.logical_key),['b','a']);assert.deepEqual(body.batch.at(-1).params,['2026-09-01T02:00:00.000Z','2','2','run','official-fpl-r1']);});
test('valid single and batch responses are accepted',async()=>{assert.equal((await createD1RestClient({...config,transport:async()=>ok(1)}).run(read())).results.length,1);const batch=buildCommitBatch({entities:[],previousRows:[],observations:[{logical_key:'a',observation_id:'1'}],completedAt:'2026-09-01T00:00:00.000Z',recordsSeen:1,runId:'r',sourceRevisionId:'official-fpl-r1'});assert.equal((await createD1RestClient({...config,transport:async()=>ok(3)}).run(batch)).results.length,3);});
test('invalid provider accounting reports only the fixed field and failure class',async()=>{for(const [field,value,reason] of [['rows_read','1','type'],['rows_written',-1,'range'],['changes',1000001,'range']]){const response={status:200,json:async()=>({success:true,result:[{success:true,results:[],meta:{[field]:value}}]})};await assert.rejects(createD1RestClient({...config,transport:async()=>response}).run(read()),error=>{assert.equal(error.code,`d1_result_contract_invalid_${field}_${reason}`);assert.doesNotMatch(String(error),/1000001|super-secret|SELECT/);return true;});}});
test('HTTP, JSON, API, result and statement failures are sanitized',async()=>{const cases=[[{status:401,json:async()=>({})},'d1_auth_failed'],[{status:403,json:async()=>({})},'d1_auth_failed'],[{status:429,json:async()=>({errors:[{message:'raw'}]})},'d1_rate_limited'],[{status:500,json:async()=>({token:'super-secret'})},'d1_http_failed'],[{status:200,json:async()=>{throw new Error('raw SQL SELECT')}} ,'d1_response_json_invalid'],[{status:200,json:async()=>({success:false,errors:[{message:'raw'}]})},'d1_api_failed'],[{status:200,json:async()=>({success:true,result:{}})},'d1_result_contract_invalid'],[{status:200,json:async()=>({success:true,result:[{success:false,error:'raw'}]})},'d1_statement_failed']];for(const [response,expected] of cases){await assert.rejects(createD1RestClient({...config,transport:async()=>response}).run(read()),error=>{assert.equal(error.code,expected);const rendered=String(error);for(const secret of ['super-secret','Authorization','SELECT','official-fpl-r1','raw'])assert.ok(!rendered.includes(secret));return true;});}});
test('read versus mutation transport failure classification and no retry',async()=>{let calls=0;const transport=async()=>{calls++;throw new Error('body and token');};await assert.rejects(createD1RestClient({...config,transport}).run(read()),code('d1_transport_failed'));assert.equal(calls,1);const mutation=buildStartRunMutation({runId:'r',sourceRevisionId:'official-fpl-r1',startedAt:'2026-09-01T00:00:00.000Z',safeEndpointClass:'safe',parserVersion:'p',transformVersion:'t',schemaVersion:'s'});await assert.rejects(createD1RestClient({...config,transport}).run(mutation),code('d1_mutation_outcome_unknown'));assert.equal(calls,2);});
test('16 MiB whole-request ceiling rejects without dispatch',async()=>{const pad='x'.repeat(1900),observations=Array.from({length:9000},(_,i)=>({logical_key:`k${i}`,observation_id:String(i).padStart(64,'0'),pad}));const plan=buildCommitBatch({entities:[],previousRows:[],observations,completedAt:'2026-09-01T00:00:00.000Z',recordsSeen:9000,runId:'r',sourceRevisionId:'official-fpl-r1'});let calls=0;await assert.rejects(createD1RestClient({...config,transport:async()=>{calls++;}}).run(plan),code('d1_request_too_large'));assert.equal(calls,0);assert.equal(D1_REST_REQUEST_LIMIT_BYTES,16*1024*1024);});
test('E1 modules contain no default fetch, environment, filesystem or logging capability',()=>{for(const file of ['workers/data-platform/d1-rest-client.mjs','workers/data-platform/official-fpl-d1-rest-plan.mjs']){const source=fs.readFileSync(file,'utf8');assert.doesNotMatch(source,/globalThis\.fetch|\bfetch\s*\(|process\.env|node:fs|console\.(?:log|error)|baseUrl|hostname/);}});
