import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import * as plan from '../workers/data-platform/e2-d1-rest-validation-plan.mjs';
import {createE2ValidationHarness,validateDisposableIdentity,E2_OUTCOME_CLASSIFICATIONS} from '../workers/data-platform/e2-d1-rest-validation-harness.mjs';
const identity={accountFingerprint:'acct-e2',approvedAccountFingerprint:'acct-e2',productionAccountFingerprint:'acct-production',databaseName:'teamsheet-data-e2-rest-validation-20260901-a1b2c3',databaseFingerprint:'db-e2',expectedDatabaseFingerprint:'db-e2',schemaFingerprint:plan.E2_SCHEMA_FINGERPRINT,expectedSchemaFingerprint:plan.E2_SCHEMA_FINGERPRINT,tables:[]};
const code=value=>error=>error?.code===value;

test('F01-F05 production firewall accepts only exact disposable identity',()=>{assert.ok(validateDisposableIdentity(identity));for(const patch of [{databaseName:'teamsheet-data'},{accountFingerprint:''},{databaseFingerprint:'wrong'},{tables:['shadow_observations']},{schemaFingerprint:'wrong'}])assert.throws(()=>validateDisposableIdentity({...identity,...patch}),E=>E instanceof Error);assert.throws(()=>validateDisposableIdentity({...identity,accountFingerprint:'acct-production',approvedAccountFingerprint:'acct-production'}),/e2_production_account_rejected/);assert.ok(validateDisposableIdentity({...identity,phase:'setup',tables:[...plan.E2_APPROVED_TABLES]}));assert.throws(()=>validateDisposableIdentity({...identity,phase:'setup',tables:['e2_other']}),/e2_unapproved_schema_table/);});
test('A01-A03 deterministic atomicity plans include runtime and syntax middle failures',()=>{const happy=plan.buildAtomicityCase('A01'),runtime=plan.buildAtomicityCase('A02'),syntax=plan.buildAtomicityCase('A03');assert.equal(happy.statements.length,3);assert.deepEqual(plan.buildAtomicityCase('A01'),happy);assert.equal(runtime.statements[1].params.at(-1),'2');assert.match(syntax.statements[1].sql,/INVALID SQL/);for(const built of [happy,runtime,syntax])for(const statement of built.statements)assert.ok(statement.params.every(value=>typeof value==='string'));});
test('A04-A06 reconciliation classifies rollback, complete, partial and ambiguity',()=>{assert.equal(plan.classifyAtomicityRows([]),'FULL_ROLLBACK');assert.equal(plan.classifyAtomicityRows([{sequence_no:1},{sequence_no:2},{sequence_no:3}]),'COMPLETE_SUCCESS');assert.equal(plan.classifyAtomicityRows([{sequence_no:1}]),'PARTIAL_WRITE');assert.equal(plan.classifyAtomicityRows([{sequence_no:99}]),'AMBIGUOUS');assert.equal(plan.buildAtomicityReconciliation().mutation,false);});
test('P01-P09 direct affinity values are strings and JSON mixed/null path is inspectable',()=>{const built=plan.buildAffinityPlan(),params=built.statements.flatMap(row=>row.params);for(const expected of ['42','3.125','0042','0','1','2026-09-01T12:34:56.000Z','true','false'])assert.ok(params.includes(expected));assert.ok(params.every(value=>typeof value==='string'));const mixed=JSON.parse(built.statements.at(-1).params[0]);assert.deepEqual(mixed.map(row=>row.value),[42,3.125,'0042',true,null]);const large=plan.buildLargeJsonAffinityPlan();assert.ok(Buffer.byteLength(large.statements[0].params[0])<2000000);});
test('L01-L06 statement profiles cover derived representative count and reject >40',()=>{for(const count of [1,10,plan.E2_REPRESENTATIVE_STATEMENTS,35,40])assert.equal(plan.buildStatementProfile(count).statements.length,count);assert.equal(plan.buildSyntheticFullWriteAnalogue().statements.length,plan.E2_REPRESENTATIVE_STATEMENTS);assert.throws(()=>plan.buildStatementProfile(41),/e2_statement_count_invalid/);});
test('L07-L11 body profiles have exact deterministic serialized bytes',()=>{assert.deepEqual(plan.E2_BODY_PROFILE_TARGETS,[922219,1844438,2766656,3688875,4611094]);for(const target of plan.E2_BODY_PROFILE_TARGETS){const built=plan.buildBodySizeProfile(target);assert.equal(plan.serializedBodyBytes(built),target);assert.equal(built.mutation,false);}});
test('W01-W02 9860 analogue mirrors 1 + 17 + 5 + 1 chunks without production data',()=>{const built=plan.buildSyntheticFullWriteAnalogue();assert.equal(built.statements.length,24);assert.equal(JSON.parse(built.statements[1].params[0]).length,600);assert.equal(JSON.parse(built.statements[17].params[0]).length,260);assert.equal(JSON.parse(built.statements[18].params[0]).length,2000);assert.equal(JSON.parse(built.statements[22].params[0]).length,1860);const raw=JSON.stringify(built);for(const forbidden of ['shadow_observations','observation_heads','canonical_entities','official-fpl-r1'])assert.doesNotMatch(raw,new RegExp(forbidden));assert.deepEqual(plan.buildSyntheticFullWriteAnalogue(),built);});
test('C01 missing transport and arbitrary options fail closed',()=>{assert.throws(()=>createE2ValidationHarness({identity}),code('e2_transport_required'));assert.throws(()=>createE2ValidationHarness({identity,transport:()=>{},baseUrl:'https://example.com'}),code('e2_transport_required'));});
test('C02-C08 fake response classifications dispatch mutation exactly once',async()=>{const cases=[[200,{success:true,result:[{success:true},{success:true},{success:true}]},'success'],[200,'not-json','malformed_provider_response'],[401,{},'auth_failure'],[403,{},'auth_failure'],[429,{},'rate_limited'],[500,{},'known_sql_provider_failure']];for(const [status,payload,expected] of cases){let calls=0;const harness=createE2ValidationHarness({identity,transport:async()=>{calls++;return {status,json:async()=>{if(typeof payload==='string')throw new Error(payload);return payload;}};}});const evidence=await harness.execute(plan.buildAtomicityCase('A01'));assert.equal(evidence.classification,expected);assert.equal(calls,1);assert.equal(evidence.dispatchCount,1);}let calls=0;const unknown=await createE2ValidationHarness({identity,transport:async()=>{calls++;throw new Error('secret raw failure');}}).execute(plan.buildAtomicityCase('A01'));assert.equal(unknown.classification,E2_OUTCOME_CLASSIFICATIONS.UNKNOWN);assert.equal(calls,1);});
test('S01-S03 evidence is bounded and excludes auth, raw bodies, responses and raw IDs',async()=>{const secret='bearer-super-secret';const evidence=await createE2ValidationHarness({identity,transport:async request=>({status:200,json:async()=>({success:true,result:[{}]})})}).execute(plan.buildAtomicityReconciliation(),{sourceSha:'abc123'});const raw=JSON.stringify(evidence);for(const forbidden of [secret,'Authorization','acct-e2','db-e2','SELECT','result'])assert.doesNotMatch(raw,new RegExp(forbidden));assert.match(evidence.accountFingerprint,/^sha256:/);assert.equal(evidence.sourceSha,'abc123');});
test('network firewall remains static: no fetch, URL, environment, logging or retry capability',()=>{for(const file of ['workers/data-platform/e2-d1-rest-validation-plan.mjs','workers/data-platform/e2-d1-rest-validation-harness.mjs']){const source=fs.readFileSync(file,'utf8');assert.doesNotMatch(source,/globalThis\.fetch|\bfetch\s*\(|https?:\/\/|process\.env|console\.(?:log|error)|Authorization|setTimeout|retry/i);}});
