import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as plan from '../workers/data-platform/e2-d1-rest-validation-plan.mjs';
import {E2_EXPECTED_SEMANTIC_SCHEMA,E2_EXPECTED_SEMANTIC_SCHEMA_FINGERPRINT,canonicalizeLiveSchema,deriveLiveSchemaFingerprint,normalizeE2CheckExpression,validateInitialLiveObjects,validateSetupLiveSchema} from '../workers/data-platform/e2-live-schema-contract.mjs';
import {createE2LiveHttpAdapter,e2IdentityFingerprint,E2_LIVE_HTTP_CAPABILITY} from '../workers/data-platform/e2-live-http-adapter.mjs';
import {E2_LIVE_RESPONSE_CLASS,runE2LiveContract,runE2LiveHttpContract,finalizeE2Evidence,validateE2AffinityRows,validateE2StorageAffinityRows} from '../workers/data-platform/e2-live-orchestrator.mjs';
import {decodeE2QueryResponse,validateE2PreMutationDiagnostic} from '../workers/data-platform/e2-live-response-decoder.mjs';

const clone=value=>structuredClone(value);
const rawAccount='acct_e2';
const rawDatabase='12345678-1234-1234-1234-123456789abc';
const identity={accountFingerprint:e2IdentityFingerprint(rawAccount),approvedAccountFingerprint:e2IdentityFingerprint(rawAccount),productionAccountFingerprint:e2IdentityFingerprint('acct-production'),databaseName:'teamsheet-data-e2-rest-validation-20260901-a1b2c3',databaseFingerprint:e2IdentityFingerprint(rawDatabase),expectedDatabaseFingerprint:e2IdentityFingerprint(rawDatabase),schemaFingerprint:plan.E2_INITIAL_SCHEMA_FINGERPRINT,tables:[]};
const finalRow={entities:1064,observations:9860,heads:9860,orphan_heads:0,run_rows:1,run_status:'completed',records_accepted:9860};

function affinityRows(){const direct=['42','3.125','0042','0','1','2026-09-01T12:34:56.000Z','{"safe":true}','true','false'],numeric=[42,3.125,42,0,1,2026,0,0,0],types=['integer','real','integer','integer','integer','integer','integer','integer','integer'];return [...direct.map((value,index)=>[{bound_type:'text',exact_value:value,numeric_value:numeric[index],numeric_type:types[index],text_equal:1,numeric_equal:1}]),[{left_value:'0042',right_value:'42',text_order:1,numeric_order:0}],[{kind:'integer',json_value_type:'integer',sqlite_value_type:'integer',exact_value:42},{kind:'real',json_value_type:'real',sqlite_value_type:'real',exact_value:3.125},{kind:'string',json_value_type:'text',sqlite_value_type:'text',exact_value:'0042'},{kind:'boolean',json_value_type:'true',sqlite_value_type:'integer',exact_value:1},{kind:'null',json_value_type:'null',sqlite_value_type:'null',exact_value:null}]];}
function storageRows(){return [{observation_id:'e2-affinity-0042',number_type:'real',value_number:42,text_type:'text',value_text:'0042'},{observation_id:'e2-affinity-42',number_type:'real',value_number:42,text_type:'text',value_text:'42'}];}
function responseFor(caseId){return {classification:['A02','A03'].includes(caseId)?E2_LIVE_RESPONSE_CLASS.SQL_FAILURE:E2_LIVE_RESPONSE_CLASS.SUCCESS,completionChanges:caseId==='W01'?1:undefined,rowsByStatement:caseId==='P01-P07'?affinityRows():undefined};}
function reconciliationFor(item){
  if(item.caseId==='SCHEMA-RECONCILE')return {metadata:clone(E2_EXPECTED_SEMANTIC_SCHEMA)};
  if(item.caseId?.startsWith('A04-'))return {rows:item.caseId.endsWith('A01')?[{sequence_no:1},{sequence_no:2},{sequence_no:3}]:[]};
  if(item.caseId==='P-STORAGE-READ')return {classification:'COMPLETE_SUCCESS',rows:storageRows()};
  if(item.caseId==='W00-R')return {rows:[{run_id:'e2-run-full-write',status:'started',records_accepted:0}]};
  return {rows:[finalRow]};
}
function options(overrides={}){return {sourceSha:'a'.repeat(40),approvedSourceSha:'a'.repeat(40),runnerIdentity:'e2c-a-runner-v1',startedAt:'2026-09-01T00:00:00.000Z',identity,initialObjects:[],query:async item=>responseFor(item.caseId),reconcile:async item=>reconciliationFor(item),...overrides};}

async function runAtomicVariant(caseId,responseClassification,rows){
  return runE2LiveContract(options({query:async item=>item.caseId===caseId?{classification:responseClassification}:responseFor(item.caseId),reconcile:async item=>item.caseId===`A04-${caseId}`?{rows}:reconciliationFor(item)}));
}

test('W00 is exact and W01 retains its independent 24-statement 2,378,752-byte mutation identity',()=>{
  assert.deepEqual(plan.buildFullWriteRunStart().statements[0].params,['e2-run-full-write','0']);
  assert.equal(plan.reconcileFullWriteRunStart([{run_id:'e2-run-full-write',status:'started',records_accepted:0}]),true);
  const w01=plan.buildSyntheticFullWriteAnalogue();assert.equal(w01.statements.length,24);assert.equal(plan.serializedBodyBytes(w01),plan.E2_W01_SERIALIZED_REQUEST_BYTES);assert.equal(plan.E2_W01_SERIALIZED_REQUEST_BYTES,2378752);
  assert.equal(plan.E2_REPRESENTATIVE_REQUEST_BYTES,3688875);assert.equal(plan.E2_BODY_PROFILE_TARGETS[3],3688875);assert.equal(plan.E2_BODY_PROFILE_TARGETS[4],4611094);
});

test('W01 reconciliation rejects zero-row completion and every count/state drift',()=>{assert.equal(plan.reconcileFullWrite([finalRow],1),true);assert.equal(plan.reconcileFullWrite([finalRow],0),false);for(const key of Object.keys(finalRow))assert.equal(plan.reconcileFullWrite([{...finalRow,[key]:key==='run_status'?'started':999}],1),false);});

test('affinity plans preserve exact strings, explicit ordering, native JSON and isolated storage probes',()=>{const affinity=plan.buildAffinityPlan(),raw=JSON.stringify(affinity);for(const value of ['42','3.125','0042','0','1','true','false'])assert.ok(affinity.statements.flatMap(row=>row.params).includes(value));for(const token of ['typeof(CAST','COLLATE BINARY','text_order','numeric_order','json_type','sqlite_value_type'])assert.match(raw,new RegExp(token.replace(/[()]/g,'\\$&')));assert.deepEqual(JSON.parse(affinity.statements.at(-1).params[0]).map(row=>row.value),[42,3.125,'0042',true,null]);assert.equal(plan.buildStorageAffinityMutation().mutation,true);assert.equal(plan.buildStorageAffinityReconciliation().mutation,false);});

test('repository-owned affinity semantics reject every returned-value drift',()=>{assert.equal(validateE2AffinityRows(affinityRows()),true);for(let statement=0;statement<affinityRows().length;statement++){const drift=affinityRows();drift[statement]=[];assert.equal(validateE2AffinityRows(drift),false);}const direct=affinityRows();direct[0][0].exact_value=42;assert.equal(validateE2AffinityRows(direct),false);assert.equal(validateE2StorageAffinityRows(storageRows()),true);for(const rows of [[],storageRows().slice().reverse(),storageRows().map((row,index)=>index?row:{...row,value_text:'42'})])assert.equal(validateE2StorageAffinityRows(rows),false);});

test('expected live semantic schema has a separate deterministic repository-owned identity',()=>{assert.equal(E2_EXPECTED_SEMANTIC_SCHEMA.length,5);assert.equal(deriveLiveSchemaFingerprint(E2_EXPECTED_SEMANTIC_SCHEMA),E2_EXPECTED_SEMANTIC_SCHEMA_FINGERPRINT);assert.equal(validateSetupLiveSchema(clone(E2_EXPECTED_SEMANTIC_SCHEMA)),E2_EXPECTED_SEMANTIC_SCHEMA_FINGERPRINT);assert.equal(canonicalizeLiveSchema(E2_EXPECTED_SEMANTIC_SCHEMA),canonicalizeLiveSchema(clone(E2_EXPECTED_SEMANTIC_SCHEMA)));assert.notEqual(E2_EXPECTED_SEMANTIC_SCHEMA_FINGERPRINT,plan.E2_SETUP_SCHEMA_FINGERPRINT);});

test('semantic validation rejects every required same-name structural drift',()=>{
  const drifts={
    column_type:s=>{s[0].columns[0].type='INTEGER';},column_order:s=>{s[0].columns.reverse();s[0].columns.forEach((v,i)=>v.cid=i);},not_null:s=>{s[0].columns[0].notnull=0;},default:s=>{s[4].columns[2].dflt_value='1';},pk_position:s=>{s[0].columns[0].pk=2;},missing_unique:s=>{s[0].indexes.pop();},unexpected_index:s=>{s[0].indexes.push(clone(s[0].indexes[0]));},index_order:s=>{s[0].indexes[0].columns.reverse();s[0].indexes[0].columns.forEach((v,i)=>v.seqno=i);},index_collation:s=>{s[0].indexes[0].columns[0].coll='NOCASE';},foreign_key_target:s=>{s[2].foreignKeys[0].table='e2_entities';},foreign_key_action:s=>{s[2].foreignKeys[0].on_delete='CASCADE';},required_check:s=>{s[0].checks=[];},extra_column:s=>{s[0].columns.push({cid:4,name:'extra',type:'TEXT',notnull:0,dflt_value:null,pk:0,hidden:0});},missing_column:s=>{s[0].columns.pop();}
  };
  for(const [name,mutate] of Object.entries(drifts)){const observed=clone(E2_EXPECTED_SEMANTIC_SCHEMA);mutate(observed);assert.throws(()=>validateSetupLiveSchema(observed),/semantic_mismatch/,name);}
});

test('CHECK extraction tolerates SQLite whitespace normalization but not changed semantics',()=>{const observed=clone(E2_EXPECTED_SEMANTIC_SCHEMA);observed[0].sql='CREATE TABLE e2_atomicity (... CHECK ( valid_value IN ( 0 , 1 ) ))';delete observed[0].checks;assert.equal(validateSetupLiveSchema(observed),E2_EXPECTED_SEMANTIC_SCHEMA_FINGERPRINT);observed[0].sql='CREATE TABLE e2_atomicity (... CHECK (valid_value IN (0,1,2)))';assert.throws(()=>validateSetupLiveSchema(observed),/semantic_mismatch/);});

test('initial schema policy rejects unknown system-looking and production objects',()=>{assert.equal(validateInitialLiveObjects([]),true);assert.equal(validateInitialLiveObjects([{type:'table',name:'sqlite_sequence'}]),true);for(const row of [{type:'table',name:'_cf_future'},{type:'view',name:'sqlite_sequence'},{type:'table',name:'shadow_observations'}])assert.throws(()=>validateInitialLiveObjects([row]));});

test('HTTP adapter accepts only authentic plans and internally owns exact metadata/query requests',async()=>{const calls=[];const adapter=createE2LiveHttpAdapter({accountId:rawAccount,databaseId:rawDatabase,token:'test-token',identity,fetchImpl:async(...args)=>{calls.push(args);return {};}});assert.deepEqual(Object.keys(adapter),['readExactMetadata','execute']);await adapter.readExactMetadata();const authentic=plan.buildStatementProfile(1);await adapter.execute(authentic);assert.equal(calls[0][1].method,'GET');assert.equal(calls[0][0],`https://api.cloudflare.com/client/v4/accounts/${rawAccount}/d1/database/${rawDatabase}`);assert.equal(calls[1][1].method,'POST');assert.equal(calls[1][0],`${calls[0][0]}/query`);assert.deepEqual(JSON.parse(calls[1][1].body),authentic.statements[0]);assert.equal(E2_LIVE_HTTP_CAPABILITY.host,'api.cloudflare.com');await assert.rejects(adapter.execute('SELECT 1'),/plan_untrusted/);await assert.rejects(adapter.execute({statements:[{sql:'DELETE FROM anything'}]}),/plan_untrusted/);assert.equal(calls.length,2);});

test('HTTP authority rejects missing, malformed, mismatched or production-equal account approval before transport',()=>{let calls=0;const make=value=>createE2LiveHttpAdapter({accountId:rawAccount,databaseId:rawDatabase,token:'x',identity:value,fetchImpl:async()=>{calls++;return {};}});for(const key of ['productionAccountFingerprint','approvedAccountFingerprint']){const missing={...identity};delete missing[key];assert.throws(()=>make(missing));}assert.throws(()=>make({...identity,productionAccountFingerprint:''}),/production_account_fingerprint_required/);assert.throws(()=>make({...identity,approvedAccountFingerprint:'sha256:malformed'}),/account_fingerprint_mismatch/);assert.throws(()=>make({...identity,approvedAccountFingerprint:e2IdentityFingerprint('other-approved-account')}),/account_fingerprint_mismatch/);assert.throws(()=>make({...identity,accountFingerprint:identity.productionAccountFingerprint,approvedAccountFingerprint:identity.productionAccountFingerprint}),/production_account_rejected/);assert.throws(()=>make({...identity,databaseName:'teamsheet-data'}));assert.throws(()=>make({...identity,databaseFingerprint:e2IdentityFingerprint('wrong')}));assert.throws(()=>createE2LiveHttpAdapter({accountId:'other',databaseId:rawDatabase,token:'x',identity,fetchImpl:async()=>{calls++;return {};}}));assert.equal(calls,0);});

test('atomicity accepts only A01 success/complete and A02/A03 known failure/full rollback',async()=>{await assert.doesNotReject(runAtomicVariant('A01',E2_LIVE_RESPONSE_CLASS.SUCCESS,[{sequence_no:1},{sequence_no:2},{sequence_no:3}]));await assert.rejects(runAtomicVariant('A01',E2_LIVE_RESPONSE_CLASS.SQL_FAILURE,[]),/a01_rejected/);for(const id of ['A02','A03']){await assert.doesNotReject(runAtomicVariant(id,E2_LIVE_RESPONSE_CLASS.SQL_FAILURE,[]));await assert.rejects(runAtomicVariant(id,E2_LIVE_RESPONSE_CLASS.SUCCESS,[]),new RegExp(`${id.toLowerCase()}_rejected`));await assert.rejects(runAtomicVariant(id,E2_LIVE_RESPONSE_CLASS.SQL_FAILURE,[{sequence_no:1}]),new RegExp(`${id.toLowerCase()}_rejected`));await assert.rejects(runAtomicVariant(id,E2_LIVE_RESPONSE_CLASS.SQL_FAILURE,[{sequence_no:1},{sequence_no:2},{sequence_no:3}]),new RegExp(`${id.toLowerCase()}_rejected`));}});

test('orchestration reaches fixed 125% gate and dispatches every mutation once',async()=>{const seen=[];const result=await runE2LiveContract(options({query:async item=>{seen.push(item.caseId);return responseFor(item.caseId);}}));assert.equal(result.state,'STOP');assert.deepEqual(seen.slice(-2),['W00','W01']);assert.equal(seen.at(seen.indexOf('A01')-1),`L-body-${plan.E2_BODY_PROFILE_TARGETS.at(-1)}`);for(const id of ['F-SCHEMA-SETUP','A01','A02','A03','P-STORAGE-WRITE','W00','W01'])assert.equal(result.dispatchCounts[id],1);});

test('every ambiguous mutation reconciles once, records state, stops, and is never retried',async()=>{for(const id of ['F-SCHEMA-SETUP','A01','A02','A03','P-STORAGE-WRITE','W00','W01']){const dispatches=[],reconciliations=[];let error;try{await runE2LiveContract(options({query:async item=>{dispatches.push(item.caseId);if(item.caseId===id)throw new Error('secret transport body');return responseFor(item.caseId);},reconcile:async item=>{reconciliations.push(item.caseId);return reconciliationFor(item);}}));}catch(value){error=value;}assert.ok(error,id);assert.equal(dispatches.filter(value=>value===id).length,1,id);const expected={"F-SCHEMA-SETUP":'SCHEMA-RECONCILE',A01:'A04-A01',A02:'A04-A02',A03:'A04-A03','P-STORAGE-WRITE':'P-STORAGE-READ',W00:'W00-R',W01:'W01-R'}[id];assert.equal(reconciliations.filter(value=>value===expected).length,1,id);const item=error.evidence.find(value=>value.testCaseId===id);assert.equal(item.responseClassification,E2_LIVE_RESPONSE_CLASS.UNKNOWN);assert.notEqual(item.reconciliationClassification,null);}});

test('failed 100% body gate stops before all atomicity and write mutations',async()=>{const seen=[];await assert.rejects(runE2LiveContract(options({query:async item=>{seen.push(item.caseId);return item.caseId===`L-body-${plan.E2_BODY_PROFILE_TARGETS[3]}`?{classification:E2_LIVE_RESPONSE_CLASS.TRANSPORT}:responseFor(item.caseId);}})),/body_profile_failed/);assert.ok(!seen.includes('A01'));assert.ok(!seen.includes('W01'));});

test('evidence rejects or bounds malicious caller/provider fields without nested passthrough',async()=>{await assert.rejects(runE2LiveContract(options({runnerIdentity:'Authorization: Bearer stolen'})),/runner_identity_invalid/);const result=await runE2LiveContract(options({query:async item=>({...responseFor(item.caseId),providerTimingMs:Infinity,totalAttempts:1000001,rowsRead:-1,rowsWritten:2.5,changes:999999999,syntheticTableCounts:{e2_runs:1,token:'stolen'},provider:{Authorization:'Bearer stolen'},rawBody:'SELECT secret'})}));const raw=JSON.stringify(result.evidence);for(const forbidden of ['Bearer stolen','SELECT secret','Authorization','"token"','"provider"','"rawBody"'])assert.doesNotMatch(raw,new RegExp(forbidden));for(const item of result.evidence){assert.equal(item.providerTimingMs,null);assert.equal(item.totalAttempts,null);assert.equal(item.rowsRead,null);assert.equal(item.rowsWritten,null);assert.equal(item.changes,null);assert.equal(item.syntheticTableCounts,null);}});

test('static authority surface has no generic Cloudflare or production mutation path',()=>{const files=['workers/data-platform/e2-live-http-adapter.mjs','workers/data-platform/e2-live-response-decoder.mjs','workers/data-platform/e2-live-orchestrator.mjs'];const raw=files.map(file=>fs.readFileSync(file,'utf8')).join('\n');for(const forbidden of ['wrangler deploy','set -x','/workers/scripts','/access/','/secrets','/zones','/routes','database/create','database/delete','console.log','process.env','listDatabases','baseUrl'])assert.doesNotMatch(raw,new RegExp(forbidden.replace('/','\\/'),'i'));});

function cloudflareResponse(status,payload,{malformed=false}={}){return {status,json:async()=>{if(malformed)throw new Error('raw provider secret');return clone(payload);}};}
function successResults(planValue,rowsByStatement=[],lastChanges=0){return {success:true,result:planValue.statements.map((_,index)=>({success:true,results:rowsByStatement[index]||[],meta:{rows_read:(rowsByStatement[index]||[]).length,rows_written:0,changes:index===planValue.statements.length-1?lastChanges:0,duration:1}}))};}
function schemaRows(){
  const schema=E2_EXPECTED_SEMANTIC_SCHEMA.map(table=>({type:'table',name:table.name,tbl_name:table.name,sql:`CREATE TABLE ${table.name} (x TEXT${table.checks.length?`, ${table.checks.map(check=>`CHECK (${check})`).join(', ')}`:''})`}));
  for(const table of E2_EXPECTED_SEMANTIC_SCHEMA)for(let index=0;index<table.indexes.length;index++)schema.push({type:'index',name:`e2_test_${table.name}_${index}`,tbl_name:table.name,sql:null});
  const rows=[schema];
  for(const tableName of plan.E2_APPROVED_TABLES){
    const table=E2_EXPECTED_SEMANTIC_SCHEMA.find(item=>item.name===tableName);
    const named=table.indexes.map((item,index)=>({...item,seq:index,name:`e2_test_${tableName}_${index}`}));
    rows.push(clone(table.columns));
    rows.push(named.map(({seq,name,unique,origin,partial})=>({seq,name,unique,origin,partial})));
    rows.push(named.flatMap(item=>item.columns.map(column=>({...column,index_name:item.name}))));
    rows.push(clone(table.foreignKeys));
  }
  return rows;
}
function identifyBody(body){if(body===undefined)return 'METADATA';const value=JSON.parse(body),statements=value.batch||[value];if(statements[0].sql.startsWith('CREATE TABLE'))return 'F-SCHEMA-SETUP';if(statements.length===21&&statements[0].sql.includes('sqlite_schema'))return 'SCHEMA-RECONCILE';if(statements.length===11&&statements[0].sql.includes('bound_type'))return 'P01-P07';const params=statements.flatMap(item=>item.params||[]);for(const id of ['A01','A02','A03'])if(params.includes(`e2-run-${id.toLowerCase()}`))return statements[0].sql.startsWith('SELECT')?`A04-${id}`:id;if(statements[0].sql.includes("LIKE 'e2|affinity|%'"))return 'P-STORAGE-READ';if(statements[0].sql.includes('e2-affinity-42'))return 'P-STORAGE-WRITE';if(statements[0].sql.startsWith('SELECT run_id,status'))return 'W00-R';if(statements[0].sql.startsWith('INSERT INTO e2_runs'))return 'W00';if(statements[0].sql.includes('(SELECT count(*) FROM e2_entities)'))return 'W01-R';if(statements.length===24&&statements.at(-1).sql.startsWith('UPDATE e2_runs'))return 'W01';return 'READ-PROFILE';}
function integratedFetch({override}={}){const calls=[];let schemaReads=0;const fetchImpl=async(url,request)=>{calls.push({url,request});if(request.method==='GET'){if(override){const value=await override('METADATA',calls.length,url,request);if(value!==undefined)return value;}return cloudflareResponse(200,{success:true,result:{uuid:rawDatabase,name:identity.databaseName}});}const id=identifyBody(request.body);if(override){const value=await override(id,calls.length,url,request);if(value!==undefined)return value;}let built;if(id==='SCHEMA-RECONCILE'){built=plan.buildSchemaInspectionPlan();schemaReads++;return cloudflareResponse(200,successResults(built,schemaReads===1?Array.from({length:built.statements.length},()=>[]):schemaRows()));}if(id==='P01-P07')return cloudflareResponse(200,successResults(plan.buildAffinityPlan(),affinityRows()));if(id.startsWith('A04-')){built=plan.buildAtomicityReconciliation(id.slice(4));const rows=id.endsWith('A01')?[{sequence_no:1},{sequence_no:2},{sequence_no:3}]:[];return cloudflareResponse(200,successResults(built,[rows]));}if(id==='P-STORAGE-READ')return cloudflareResponse(200,successResults(plan.buildStorageAffinityReconciliation(),[storageRows()]));if(id==='W00-R')return cloudflareResponse(200,successResults(plan.buildFullWriteRunStartReconciliation(),[[{run_id:'e2-run-full-write',status:'started',records_accepted:0}]]));if(id==='W01-R')return cloudflareResponse(200,successResults(plan.buildFullWriteReconciliation(),[[finalRow]]));if(id==='A02'||id==='A03'){built=plan.buildAtomicityCase(id);const result=built.statements.map((_,index)=>({success:index!==1,results:[],meta:{changes:0}}));return cloudflareResponse(200,{success:true,result});}const builders={A01:()=>plan.buildAtomicityCase('A01'),'F-SCHEMA-SETUP':plan.buildSyntheticSchemaSetupPlan,'P-STORAGE-WRITE':plan.buildStorageAffinityMutation,W00:plan.buildFullWriteRunStart,W01:plan.buildSyntheticFullWriteAnalogue};built=builders[id]?.();if(!built){const parsed=JSON.parse(request.body),count=(parsed.batch||[parsed]).length;return cloudflareResponse(200,{success:true,result:Array.from({length:count},()=>({success:true,results:[],meta:{changes:0}}))});}return cloudflareResponse(200,successResults(built,[],id==='W01'?1:0));};return {calls,fetchImpl};}
function liveOptions(fetchImpl,overrides={}){const base=options();delete base.query;delete base.reconcile;return {...base,accountId:rawAccount,databaseId:rawDatabase,token:'synthetic-token',fetchImpl,...overrides};}

test('strict decoder derives closed classifications and bounded metadata from Cloudflare-shaped responses',async()=>{const read=plan.buildStatementProfile(1),mutation=plan.buildFullWriteRunStart();assert.equal((await decodeE2QueryResponse(cloudflareResponse(200,successResults(read,[[{value:1}]])),read)).classification,E2_LIVE_RESPONSE_CLASS.SUCCESS);assert.equal((await decodeE2QueryResponse(cloudflareResponse(200,{success:true,result:[{success:false}]}),mutation)).classification,E2_LIVE_RESPONSE_CLASS.SQL_FAILURE);for(const status of [401,403])assert.equal((await decodeE2QueryResponse(cloudflareResponse(status,{}),read)).classification,E2_LIVE_RESPONSE_CLASS.AUTH);assert.equal((await decodeE2QueryResponse(cloudflareResponse(429,{}),read)).classification,E2_LIVE_RESPONSE_CLASS.RATE);assert.equal((await decodeE2QueryResponse(cloudflareResponse(500,{}),read)).classification,E2_LIVE_RESPONSE_CLASS.TRANSPORT);assert.equal((await decodeE2QueryResponse(cloudflareResponse(500,{}),mutation)).classification,E2_LIVE_RESPONSE_CLASS.UNKNOWN);for(const response of [cloudflareResponse(200,{}, {malformed:true}),cloudflareResponse(200,{success:true,result:[]}),cloudflareResponse(200,{success:true,result:[{}]}),cloudflareResponse(200,{success:true,result:[{success:true,meta:{changes:'1'}}]})])assert.equal((await decodeE2QueryResponse(response,read)).classification,E2_LIVE_RESPONSE_CLASS.MALFORMED);});

test('decoder distinguishes absent provider metadata from genuine zero and bounds total attempts',async()=>{const read=plan.buildStatementProfile(1);const absent=await decodeE2QueryResponse(cloudflareResponse(200,{success:true,result:[{success:true,results:[]}]}),read);assert.deepEqual([absent.rowsRead,absent.rowsWritten,absent.changes,absent.providerTimingMs,absent.totalAttempts],[null,null,null,null,null]);const zero=await decodeE2QueryResponse(cloudflareResponse(200,{success:true,result:[{success:true,results:[],meta:{rows_read:0,rows_written:0,changes:0,duration:0,total_attempts:0}}]}),read);assert.deepEqual([zero.rowsRead,zero.rowsWritten,zero.changes,zero.providerTimingMs,zero.totalAttempts],[0,0,0,0,0]);const attempts=await decodeE2QueryResponse(cloudflareResponse(200,{success:true,result:[{success:true,results:[],meta:{total_attempts:3}}]}),read);assert.equal(attempts.totalAttempts,3);for(const value of [-1,1.5,1000001,'1'])assert.equal((await decodeE2QueryResponse(cloudflareResponse(200,{success:true,result:[{success:true,meta:{total_attempts:value}}]}),read)).classification,E2_LIVE_RESPONSE_CLASS.MALFORMED);});

test('integrated fake fetch closes authentic adapter, decoder, trusted reads and orchestration end to end',async()=>{const fake=integratedFetch();const result=await runE2LiveHttpContract(liveOptions(fake.fetchImpl));assert.equal(result.state,'STOP');for(const id of ['F-SCHEMA-SETUP','A01','A02','A03','P-STORAGE-WRITE','W00','W01'])assert.equal(result.dispatchCounts[id],1);assert.equal(result.evidence.find(item=>item.testCaseId==='A01').reconciliationClassification,'COMPLETE_SUCCESS');for(const id of ['A02','A03']){const item=result.evidence.find(value=>value.testCaseId===id);assert.equal(item.responseClassification,E2_LIVE_RESPONSE_CLASS.SQL_FAILURE);assert.equal(item.reconciliationClassification,'FULL_ROLLBACK');}assert.equal(result.evidence.find(item=>item.testCaseId==='W01').reconciliationClassification,'COMPLETED');assert.ok(fake.calls.some(call=>identifyBody(call.request.body)==='SCHEMA-RECONCILE'));assert.equal(fake.calls[0].request.method,'GET');assert.ok(fake.calls.slice(1).every(call=>call.request.method==='POST'&&call.url.endsWith('/query')));});

test('integrated affinity HTTP success is rejected when returned semantics drift',async()=>{const affinityFake=integratedFetch({override:async id=>{if(id!=='P01-P07')return;const rows=affinityRows();rows[0][0].bound_type='integer';return cloudflareResponse(200,successResults(plan.buildAffinityPlan(),rows));}});await assert.rejects(runE2LiveHttpContract(liveOptions(affinityFake.fetchImpl)),/affinity_failed/);assert.equal(affinityFake.calls.filter(call=>identifyBody(call.request.body)==='A01').length,0);const storageFake=integratedFetch({override:async id=>id==='P-STORAGE-READ'?cloudflareResponse(200,successResults(plan.buildStorageAffinityReconciliation(),[[storageRows()[0]]])):undefined});await assert.rejects(runE2LiveHttpContract(liveOptions(storageFake.fetchImpl)),/storage_affinity_reconciliation_failed/);assert.equal(storageFake.calls.filter(call=>identifyBody(call.request.body)==='P-STORAGE-WRITE').length,1);assert.equal(storageFake.calls.filter(call=>identifyBody(call.request.body)==='W00').length,0);});

test('integrated W01 completion is derived only from last statement metadata',async()=>{const fake=integratedFetch({override:async id=>id==='W01'?cloudflareResponse(200,successResults(plan.buildSyntheticFullWriteAnalogue(),[],0)):undefined});await assert.rejects(runE2LiveHttpContract(liveOptions(fake.fetchImpl)),/w01_reconciliation_failed/);assert.equal(fake.calls.filter(call=>identifyBody(call.request.body)==='W01').length,1);});

test('integrated transport failures classify by mutation/read, reconcile mutation once, and never leak errors',async()=>{let mutationError;const mutationFake=integratedFetch({override:async id=>{if(id==='A01')throw new Error('Authorization Bearer raw-secret-body');}});try{await runE2LiveHttpContract(liveOptions(mutationFake.fetchImpl));}catch(error){mutationError=error;}assert.ok(mutationError);const item=mutationError.evidence.find(value=>value.testCaseId==='A01');assert.equal(item.responseClassification,E2_LIVE_RESPONSE_CLASS.UNKNOWN);assert.equal(item.reconciliationClassification,'COMPLETE_SUCCESS');assert.doesNotMatch(JSON.stringify(mutationError.evidence),/raw-secret|Authorization|Bearer/);assert.equal(mutationFake.calls.filter(call=>identifyBody(call.request.body)==='A01').length,1);const readPlan=plan.buildStatementProfile(1);const readAdapter=createE2LiveHttpAdapter({accountId:rawAccount,databaseId:rawDatabase,token:'x',identity,fetchImpl:async()=>{throw new Error('secret');}});assert.equal((await readAdapter.execute(readPlan)).classification,E2_LIVE_RESPONSE_CLASS.TRANSPORT);});

test('integrated malformed and auth responses fail closed without caller classifications',async()=>{for(const [response,code] of [[cloudflareResponse(200,{}, {malformed:true}),/affinity_failed/],[cloudflareResponse(401,{}),/affinity_failed/],[cloudflareResponse(429,{}),/affinity_failed/]]){const fake=integratedFetch({override:async id=>id==='P01-P07'?response:undefined});await assert.rejects(runE2LiveHttpContract(liveOptions(fake.fetchImpl)),code);}});

test('quote-aware CHECK normalization preserves literal case and escaped quotes',()=>{assert.equal(normalizeE2CheckExpression(" KIND  in ( 'event' , 'team' ) "),normalizeE2CheckExpression("kind IN('event','team')"));for(const [left,right] of [["kind in ('event')","kind in ('EVENT')"],["status in ('started')","status in ('STARTED')"],["status in ('completed')","status in ('Completed')"]])assert.notEqual(normalizeE2CheckExpression(left),normalizeE2CheckExpression(right));assert.equal(normalizeE2CheckExpression("name = 'owner''s'"),"name = 'owner''s'");assert.throws(()=>normalizeE2CheckExpression("name='unclosed"),/quote_invalid/);assert.notEqual(normalizeE2CheckExpression('value in (0,1)'),normalizeE2CheckExpression('value in (0,1,2)'));});

test('evidence timestamps require canonical start and separately finalized genuine end',async()=>{for(const startedAt of ['Authorization Bearer token','2026-02-30T00:00:00.000Z','x'.repeat(200)])await assert.rejects(runE2LiveContract(options({startedAt})),/timestamp_invalid/);await assert.rejects(runE2LiveContract(options({endedAt:'2026-09-01T00:01:00.000Z'})),/runner_config_invalid/);const result=await runE2LiveContract(options());assert.ok(result.evidence.every(item=>!Object.hasOwn(item,'endedAt')));const finalized=finalizeE2Evidence(result.evidence,'2026-09-01T00:01:00.000Z');for(const item of finalized){assert.match(item.startedAt,/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/);assert.equal(item.endedAt,'2026-09-01T00:01:00.000Z');}for(const endedAt of ['token','2026-09-01T00:00:00Z','2026-02-30T00:00:00.000Z','2026-08-31T23:59:59.999Z'])assert.throws(()=>finalizeE2Evidence(result.evidence,endedAt),/timestamp_invalid/);assert.throws(()=>finalizeE2Evidence(finalized,'2026-09-01T00:02:00.000Z'),/timestamp_invalid/);});

test('closed HTTP preflight rejects metadata identity and shape before every mutation',async()=>{const cases=[
  cloudflareResponse(200,{success:true,result:{uuid:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',name:identity.databaseName}}),
  cloudflareResponse(200,{success:true,result:{uuid:rawDatabase,name:'teamsheet-data-e2-rest-validation-20260901-ffffff'}}),
  cloudflareResponse(200,{success:true,result:{name:identity.databaseName}}),
  cloudflareResponse(200,{success:true,result:{uuid:rawDatabase,name:'teamsheet-data'}})
];for(const response of cases){const fake=integratedFetch({override:async id=>id==='METADATA'?response:undefined});await assert.rejects(runE2LiveHttpContract(liveOptions(fake.fetchImpl)),/database_metadata_rejected/);assert.equal(fake.calls.filter(call=>identifyBody(call.request.body)==='F-SCHEMA-SETUP').length,0);assert.equal(fake.calls.filter(call=>identifyBody(call.request.body)==='SCHEMA-RECONCILE').length,0);}});

test('closed HTTP preflight rejects every dirty initial object class before mutation',async()=>{const objects=[
  [{type:'table',name:'unrelated',tbl_name:'unrelated',sql:'CREATE TABLE unrelated(x)'}],
  [{type:'table',name:'shadow_observations',tbl_name:'shadow_observations',sql:'CREATE TABLE shadow_observations(x)'}],
  [{type:'table',name:'e2_runs',tbl_name:'e2_runs',sql:'CREATE TABLE e2_runs(x)'}],
  [{type:'view',name:'unexpected_view',tbl_name:'unexpected_view',sql:'CREATE VIEW unexpected_view AS SELECT 1'}],
  [{type:'trigger',name:'unexpected_trigger',tbl_name:'x',sql:'CREATE TRIGGER unexpected_trigger AFTER INSERT ON x BEGIN SELECT 1; END'}],
  [{type:'index',name:'unexpected_index',tbl_name:'x',sql:'CREATE INDEX unexpected_index ON x(y)'}],
  [{type:'table',name:'_cf_future',tbl_name:'_cf_future',sql:'CREATE TABLE _cf_future(x)'}]
];for(const initialObjects of objects){let schemaCount=0;const fake=integratedFetch({override:async id=>{if(id!=='SCHEMA-RECONCILE')return undefined;schemaCount++;if(schemaCount!==1)return undefined;const built=plan.buildSchemaInspectionPlan(),rows=Array.from({length:built.statements.length},()=>[]);rows[0]=initialObjects;return cloudflareResponse(200,successResults(built,rows));}});await assert.rejects(runE2LiveHttpContract(liveOptions(fake.fetchImpl)),/initial_schema_rejected/);assert.equal(fake.calls.filter(call=>identifyBody(call.request.body)==='F-SCHEMA-SETUP').length,0);}});

test('malformed initial inspection fails before mutation',async()=>{let schemaCount=0;const fake=integratedFetch({override:async id=>{if(id==='SCHEMA-RECONCILE'&&++schemaCount===1)return cloudflareResponse(200,{success:true,result:[]});}});await assert.rejects(runE2LiveHttpContract(liveOptions(fake.fetchImpl)),/initial_schema_inspection_failed/);assert.equal(fake.calls.filter(call=>identifyBody(call.request.body)==='F-SCHEMA-SETUP').length,0);});

test('initial schema failures retain exactly one closed diagnostic and never reach setup',async()=>{
  const built=plan.buildSchemaInspectionPlan(),valid=successResults(built,Array.from({length:21},()=>[])),secret='Authorization Bearer token SELECT raw-account raw-database provider-message '+('x'.repeat(10000));
  const cases=[
    ['401',async()=>cloudflareResponse(401,{secret}),'auth_failure','http_status'],['403',async()=>cloudflareResponse(403,{secret}),'auth_failure','http_status'],['429',async()=>cloudflareResponse(429,{secret}),'rate_limited','http_status'],['500',async()=>cloudflareResponse(500,{secret}),'transport_failure','http_status'],
    ['transport',async()=>{throw new Error(secret);},'transport_failure','transport_exception'],['json',async()=>cloudflareResponse(200,{}, {malformed:true}),'malformed_provider_response','json_parse'],['envelope',async()=>cloudflareResponse(200,{secret}),'malformed_provider_response','malformed_envelope'],['api',async()=>cloudflareResponse(200,{success:false,errors:[{message:secret}]}),'known_sql_provider_failure','top_level_failure'],
    ['count',async()=>cloudflareResponse(200,{success:true,result:[]}),'malformed_provider_response','result_count'],['missing-success',async()=>cloudflareResponse(200,{...valid,result:valid.result.map((item,index)=>index?item:{results:[],secret})}),'malformed_provider_response','result_success'],['false-success',async()=>cloudflareResponse(200,{...valid,result:valid.result.map((item,index)=>index?item:{success:false,error:secret})}),'known_sql_provider_failure','unsuccessful_result'],['results',async()=>cloudflareResponse(200,{...valid,result:valid.result.map((item,index)=>index?item:{...item,results:{secret}})}),'malformed_provider_response','invalid_results'],['meta',async()=>cloudflareResponse(200,{...valid,result:valid.result.map((item,index)=>index?item:{...item,meta:{duration:secret}})}),'malformed_provider_response','malformed_meta']
  ];
  for(const [name,response,classification,reason] of cases){const fake=integratedFetch({override:async id=>id==='SCHEMA-RECONCILE'?response():undefined});let failure;try{await runE2LiveHttpContract(liveOptions(fake.fetchImpl));}catch(error){failure=error;}assert.equal(failure?.code,'e2_initial_schema_inspection_failed',name);assert.equal(failure.preMutationDiagnostics.length,1,name);assert.equal(failure.preMutationDiagnostics[0].stage,'initial_schema',name);assert.equal(failure.preMutationDiagnostics[0].classification,classification,name);assert.equal(failure.preMutationDiagnostics[0].reason,reason,name);assert.equal(fake.calls.filter(call=>identifyBody(call.request.body)==='F-SCHEMA-SETUP').length,0,name);assert.doesNotMatch(JSON.stringify(failure.preMutationDiagnostics),/Authorization|Bearer|SELECT|raw-account|raw-database|provider-message|x{100}/,name);}
});

test('valid 21-result initial schema diagnostic preserves ordering without changing acceptance',async()=>{const fake=integratedFetch();await runE2LiveHttpContract(liveOptions(fake.fetchImpl));assert.deepEqual(fake.calls.slice(0,3).map(call=>identifyBody(call.request.body)),['METADATA','SCHEMA-RECONCILE','F-SCHEMA-SETUP']);});

test('pre-mutation diagnostic schema rejects unknown keys, enums, types and out-of-range numbers',()=>{const sample={stage:'initial_schema',reason:'result_count',classification:'malformed_provider_response',httpStatus:200,jsonParsed:true,topLevelSuccessPresent:true,topLevelSuccessValue:true,expectedResultCount:21,observedResultCount:0,missingOrNonBooleanSuccessCount:0,unsuccessfulResultCount:0,invalidResultsCount:0,malformedMetaCount:0,firstFailingResultIndex:null};assert.deepEqual(validateE2PreMutationDiagnostic(sample),sample);for(const changed of [{...sample,unknown:'x'},{...sample,stage:'other'},{...sample,reason:'raw reason'},{...sample,classification:'anything'},{...sample,httpStatus:600},{...sample,expectedResultCount:41},{...sample,observedResultCount:-1},{...sample,firstFailingResultIndex:21},{...sample,jsonParsed:'true'}])assert.throws(()=>validateE2PreMutationDiagnostic(changed),/diagnostic_invalid/);});

test('dirty initial schema remains semantic rejection without a decoder diagnostic error',async()=>{const object={type:'table',name:'unexpected',tbl_name:'unexpected',sql:'CREATE TABLE unexpected(secret)'};let schemaCount=0;const fake=integratedFetch({override:async id=>{if(id!=='SCHEMA-RECONCILE'||++schemaCount!==1)return;const built=plan.buildSchemaInspectionPlan(),rows=Array.from({length:built.statements.length},()=>[]);rows[0]=[object];return cloudflareResponse(200,successResults(built,rows));}});let failure;try{await runE2LiveHttpContract(liveOptions(fake.fetchImpl));}catch(error){failure=error;}assert.equal(failure.code,'e2_initial_schema_rejected');assert.equal(failure.preMutationDiagnostics,undefined);assert.equal(fake.calls.filter(call=>identifyBody(call.request.body)==='F-SCHEMA-SETUP').length,0);});

test('metadata and clean initial schema are ordered before exactly one setup mutation',async()=>{const fake=integratedFetch();await runE2LiveHttpContract(liveOptions(fake.fetchImpl));const ids=fake.calls.map(call=>identifyBody(call.request.body));assert.equal(ids[0],'METADATA');assert.equal(ids[1],'SCHEMA-RECONCILE');assert.equal(ids[2],'F-SCHEMA-SETUP');assert.equal(ids.filter(id=>id==='F-SCHEMA-SETUP').length,1);});

test('post-setup schema rejects extra objects despite perfect five-table semantics',async()=>{let schemaCount=0;const fake=integratedFetch({override:async id=>{if(id!=='SCHEMA-RECONCILE'||++schemaCount===1)return undefined;const rows=schemaRows();rows[0].push({type:'view',name:'hidden_extra',tbl_name:'hidden_extra',sql:'CREATE VIEW hidden_extra AS SELECT 1'});return cloudflareResponse(200,successResults(plan.buildSchemaInspectionPlan(),rows));}});await assert.rejects(runE2LiveHttpContract(liveOptions(fake.fetchImpl)),/setup_failed/);assert.equal(fake.calls.filter(call=>identifyBody(call.request.body)==='F-SCHEMA-SETUP').length,1);assert.equal(fake.calls.filter(call=>identifyBody(call.request.body)==='A01').length,0);});
