import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {buildCurrentHeadsRead,buildProductionCurrentHeadsExplainRead,buildProductionGovernanceRead,buildProductionPostflightRead,buildRunRead,inspectOfficialFplD1RestPlan,validateProductionCurrentHeadsExplain} from '../workers/data-platform/official-fpl-d1-rest-plan.mjs';

const migrations=['0001_shadow_data_foundation.sql','0002_official_fpl_structured_history.sql','0003_production_query_plan_indexes.sql'];
const read=name=>fs.readFileSync(`workers/data-platform/migrations/${name}`,'utf8');
const sqlite=(db,input)=>{const out=spawnSync('sqlite3',[db],{input,encoding:'utf8'});if(out.status!==0)throw new Error(out.stderr);return out.stdout;};
const explain=(db,plan)=>sqlite(db,`EXPLAIN QUERY PLAN ${plan.statements[0].sql.replaceAll('?',"'official-fpl-r1'")};`).trim().split('\n');

function database(count=100){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'data-s2-plan-')),db=path.join(dir,'schema.db');sqlite(db,read(migrations[0])+read(migrations[1]));const seed=`INSERT INTO ingestion_runs VALUES('run','official-fpl-r1','official_fpl_structured_history','shadow_only','2026-09-02T17:41:00.000Z','2026-09-02T18:00:00.000Z','completed','official_fpl_public_core','data-s2a-official-fpl-validation-v2','data-s2a-official-fpl-history-v1','data-s2a-v1',${count},${count},0,0,NULL,'2026-09-02T17:41:00.000Z');\n`+Array.from({length:count},(_,i)=>`INSERT INTO canonical_entities VALUES('e${i}','player','2026-27','official_fpl','${i}','x');INSERT INTO shadow_observations(observation_id,logical_key,ingestion_run_id,source_revision_id,category,subject_type,subject_entity_id,provenance_kind,metric,value_type,value_number,transform_version,validation_version,input_revision,admission_state,quality_state,mode,fetched_at,created_at) VALUES('${String(i).padStart(64,'0')}','k${i}','run','official-fpl-r1','player','player','e${i}','canonical_native_fpl','cost','number',1,'t','v','i${i}','accepted','fresh','shadow_only','x','x');INSERT INTO observation_heads VALUES('k${i}','${String(i).padStart(64,'0')}','x');`).join('\n');sqlite(db,seed);return {db,dir};}

test('migration ordering is append-only and existing migration bytes remain accepted',()=>{assert.deepEqual(fs.readdirSync('workers/data-platform/migrations').filter(x=>/^\d{4}_/.test(x)).sort(),migrations);assert.equal(read(migrations[0]).length,6832);assert.equal(read(migrations[1]).length,1162);assert.match(read(migrations[2]),/CREATE INDEX observation_heads_observation_id ON observation_heads\(observation_id\)/);});

test('0003 is additive, ordered, and repeat application fails without duplicating its ledger row',()=>{const {db,dir}=database(0);try{sqlite(db,read(migrations[2]));assert.equal(sqlite(db,"SELECT group_concat(version||':'||name,',') FROM (SELECT * FROM schema_migrations ORDER BY version);").trim(),'1:shadow_data_foundation,2:official_fpl_structured_history,3:production_query_plan_indexes');const second=spawnSync('sqlite3',[db],{input:read(migrations[2]),encoding:'utf8'});assert.notEqual(second.status,0);assert.equal(sqlite(db,'SELECT COUNT(*) FROM schema_migrations WHERE version=3;').trim(),'1');}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('current-head defect is reproduced before 0003 and fixed to indexed lookup after it',()=>{const {db,dir}=database();try{const plan=inspectOfficialFplD1RestPlan(buildCurrentHeadsRead({sourceRevisionId:'official-fpl-r1'}));const before=explain(db,plan);assert.ok(before.some(x=>x.includes('SCAN h')));sqlite(db,read(migrations[2]));const after=explain(db,plan);assert.ok(after.some(x=>x.includes('SEARCH h USING COVERING INDEX observation_heads_observation_id')));assert.ok(!after.some(x=>x.includes('SCAN h')));}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('all production SELECT plans expose the complete static traversal structure at schema 0003',()=>{const {db,dir}=database();try{sqlite(db,read(migrations[2]));const plans=[buildProductionGovernanceRead({sourceRevisionId:'official-fpl-r1'}),buildRunRead({runId:'run',sourceRevisionId:'official-fpl-r1'}),buildCurrentHeadsRead({sourceRevisionId:'official-fpl-r1'}),buildProductionPostflightRead({runId:'run',sourceRevisionId:'official-fpl-r1'})];for(const plan of plans){const rows=explain(db,inspectOfficialFplD1RestPlan(plan));assert.ok(rows.every(x=>!x.includes('AUTOMATIC INDEX')),rows.join('\n'));}const heads=explain(db,plans[2]);assert.ok(heads.every(x=>!x.includes('SCAN h')));const post=explain(db,plans[3]);assert.ok(post.some(x=>x.includes('SCAN h')));assert.ok(post.some(x=>x.includes('sqlite_autoindex_shadow_observations_1')));assert.equal(post.filter(x=>x.includes('shadow_observation_idempotency')).length,1,post.join('\n'));assert.equal((inspectOfficialFplD1RestPlan(plans[3]).statements[0].sql.match(/FROM shadow_observations/g)||[]).length,1);assert.equal((inspectOfficialFplD1RestPlan(plans[3]).statements[0].sql.match(/FROM observation_heads/g)||[]).length,1);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('future live-plan acceptance is fixed to the repository current-head SQL and exact migration-3 index',()=>{const plan=inspectOfficialFplD1RestPlan(buildProductionCurrentHeadsExplainRead({sourceRevisionId:'official-fpl-r1'}));assert.equal(plan.statements.length,1);assert.match(plan.statements[0].sql,/^EXPLAIN QUERY PLAN SELECT o\.\* FROM observation_heads/);assert.deepEqual([...plan.statements[0].params],['official-fpl-r1']);assert.equal(validateProductionCurrentHeadsExplain([{detail:'SEARCH o USING INDEX shadow_observation_idempotency'},{detail:'SEARCH h USING COVERING INDEX observation_heads_observation_id (observation_id=?)'},{detail:'SEARCH r USING INDEX sqlite_autoindex_ingestion_runs_2'}]),true);for(const rows of [[],[{detail:'SCAN h'}],[{detail:'SEARCH h USING AUTOMATIC INDEX'}]])assert.throws(()=>validateProductionCurrentHeadsExplain(rows),/production_query_plan_mismatch/);assert.throws(()=>buildProductionCurrentHeadsExplainRead({sourceRevisionId:''}),/source_revision_invalid/);});
