import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {assertUploadMutation,buildVersionMetadata,capturePreUploadSnapshot,deterministicIdentity,EXPECTED_ACTIVE_VERSION_ID,EXPECTED_COMPATIBILITY_DATE,EXPECTED_CRON,EXPECTED_ROLLBACK_VERSION_ID,EXPECTED_SEASON,MODULE_PATHS,parseAndValidateConfig,requireUploadedVersionIdentity,validateModuleGraph,validateVersionDelta,WORKER_NAME} from '../workers/data-platform/phase4b/upload-version.mjs';
import {parseAndValidateConfig as phase2Config} from '../workers/data-platform/phase2/upload-version.mjs';
const config=fs.readFileSync('workers/data-platform/wrangler.jsonc','utf8');const helper=fs.readFileSync('workers/data-platform/phase4b/upload-version.mjs','utf8');const workflow=fs.readFileSync('.github/workflows/data-s2b-phase4b-version-upload.yml','utf8');
test('Phase 4B accepts exact candidate config while frozen Phase 2 rejects it',()=>{assert.equal(parseAndValidateConfig(config).triggers.crons[0],EXPECTED_CRON);assert.throws(()=>phase2Config(config),/phase2_triggers_drift/);});
test('identity, compatibility, season and module allowlist are exact',()=>{assert.equal(WORKER_NAME,'teamsheet-data-platform');assert.equal(EXPECTED_ACTIVE_VERSION_ID,'733093ef-e01f-43a8-828a-0c8c67e7626f');assert.equal(EXPECTED_COMPATIBILITY_DATE,'2026-08-22');assert.equal(EXPECTED_SEASON,'2026-27');assert.deepEqual(MODULE_PATHS.map(x=>x.split('/').at(-1)),['data-platform-rpc.mjs','data-platform.mjs','data-platform-core.mjs','official-fpl-history.mjs']);validateModuleGraph();});
test('module and metadata hashes are deterministic',()=>{const sources=validateModuleGraph(),meta=buildVersionMetadata(EXPECTED_ACTIVE_VERSION_ID,'a'.repeat(40));assert.deepEqual(deterministicIdentity(meta,sources),deterministicIdentity(meta,sources));assert.match(deterministicIdentity(meta,sources).metadata_sha256,/^[a-f0-9]{64}$/);});
test('metadata uses API-required latest only for inherited D1 and retained secret without serialising a secret value or UUID',()=>{const value=buildVersionMetadata(EXPECTED_ACTIVE_VERSION_ID,'a'.repeat(40));assert.deepEqual(value.bindings,[{name:'TEAMSHEET_DATA_DB',type:'inherit',version_id:'latest'},{name:'DATA_S1_HTTP_AUTH_TOKEN',type:'inherit',version_id:'latest'},{name:'DATA_S2_SEASON',type:'plain_text',text:'2026-27'}]);const inherited=value.bindings.filter(row=>row.type==='inherit');assert.equal(inherited.length,2);assert.ok(inherited.every(row=>row.version_id==='latest'));assert.equal(JSON.stringify(value).includes(EXPECTED_ACTIVE_VERSION_ID),false);assert.equal(JSON.stringify(value).includes('secret_text'),false);});
test('upload mutation allowlist permits only the exact versions POST',()=>{const base='/accounts/a/workers/scripts/teamsheet-data-platform';assert.equal(assertUploadMutation('POST',`${base}/versions?bindings_inherit=strict`,base),true);for(const path of [`${base}/deployments`,`${base}/schedules`,`${base}`,`${base}/secrets`,`/accounts/a/workers/domains`,`/accounts/a/access/apps`,`/accounts/a/d1/database/x/query`])assert.throws(()=>assertUploadMutation('POST',path,base),/mutation_endpoint_forbidden/);});
test('upload is one-shot and ambiguous outcomes stop for separate reconciliation without retry',()=>{assert.match(helper,/phase4b_upload_outcome_ambiguous_reconciliation_required_no_retry/);assert.doesNotMatch(helper,/catch\(error\)[\s\S]{0,500}submitVersionUpload/);assert.doesNotMatch(helper,/wrangler\s+(?:deploy|triggers)/);assert.doesNotMatch(helper,/\/schedules[^`'"\n]*[\s\S]{0,80}method:\s*'POST'/);});
test('final latest/active and rollback checks are adjacent to and precede the only upload mutation',()=>{const finalList=helper.indexOf('const versionsBefore=extractVersions');const snapshot=helper.indexOf('const preUpload=capturePreUploadSnapshot');const mutation=helper.indexOf('const uploadResult=await submitVersionUpload');assert.ok(finalList>0&&snapshot>finalList&&mutation>snapshot);assert.match(helper.slice(finalList,mutation),/requireLatestActiveVersion/);assert.match(helper.slice(finalList,mutation),/EXPECTED_ROLLBACK_VERSION_ID/);assert.doesNotMatch(helper.slice(finalList,mutation),/await health|readPhase1State|validateModuleGraph/);});
test('pre-upload snapshot pins deployment, ordered versions, provenance anchors, D1, Cron, hostname and health',()=>{const snapshot=capturePreUploadSnapshot({deployment:{deploymentId:'deployment',versionId:EXPECTED_ACTIVE_VERSION_ID},versionIds:[EXPECTED_ACTIVE_VERSION_ID,'3a2b065a-6527-4887-9bf8-b08e82e81133'],databaseId:'01e2b4f9-313a-4a14-8ce6-86c5aecc50d7',domains:['data.fpltsheet.co.uk'],schedules:[{cron:EXPECTED_CRON}],database:{file_size:151552},state:{counts:0},health:{ok:true,mode:'shadow_only'}});assert.deepEqual(snapshot.versionIds,[EXPECTED_ACTIVE_VERSION_ID,'3a2b065a-6527-4887-9bf8-b08e82e81133']);assert.equal(snapshot.expectedLatestVersionId,EXPECTED_ACTIVE_VERSION_ID);assert.equal(snapshot.rollbackPresent,true);assert.equal(snapshot.cronCount,1);assert.equal(snapshot.hostname,'data.fpltsheet.co.uk');for(const drift of [{deployment:{deploymentId:'deployment',versionId:'drift'}},{versionIds:[EXPECTED_ROLLBACK_VERSION_ID,EXPECTED_ACTIVE_VERSION_ID]},{versionIds:[EXPECTED_ACTIVE_VERSION_ID]}])assert.throws(()=>capturePreUploadSnapshot({deployment:{deploymentId:'deployment',versionId:EXPECTED_ACTIVE_VERSION_ID},versionIds:[EXPECTED_ACTIVE_VERSION_ID,'3a2b065a-6527-4887-9bf8-b08e82e81133'],databaseId:'01e2b4f9-313a-4a14-8ce6-86c5aecc50d7',domains:['data.fpltsheet.co.uk'],schedules:[{cron:EXPECTED_CRON}],database:{file_size:151552},state:{},health:{ok:true},...drift}),/preupload_snapshot_invalid|latest_version_not_active/);});
test('post-upload provenance requires exactly one returned newest delta and both anchor Versions',()=>{const before=[EXPECTED_ACTIVE_VERSION_ID,'3a2b065a-6527-4887-9bf8-b08e82e81133'],candidate='11111111-1111-4111-8111-111111111111';assert.equal(validateVersionDelta(before,[candidate,...before],candidate),true);for(const after of [[...before],[candidate,'22222222-2222-4222-8222-222222222222',...before],[...before,candidate],[candidate,EXPECTED_ACTIVE_VERSION_ID]])assert.throws(()=>validateVersionDelta(before,after,candidate),/version_delta_invalid|provenance_anchors_missing/);});
test('definite Cloudflare 4xx stays definite while 5xx, transport and malformed upload responses require reconciliation',()=>{assert.match(helper,/ambiguous&&response\.status>=500/);assert.match(helper,/throw new Error\(extractCloudflareError\(response\.status,text,sensitive\)\)/);assert.equal((helper.match(/await submitVersionUpload\(\{/g)||[]).length,1);});
test('successful POST with missing or unusable candidate identity is ambiguous and requires separate reconciliation',()=>{for(const result of [{},{id:''},{id:null},{id:42},{id:'not-a-version-id'},{id:'11111111-1111-1111-1111-111111111111'},{id:EXPECTED_ACTIVE_VERSION_ID}])assert.throws(()=>requireUploadedVersionIdentity(result,EXPECTED_ACTIVE_VERSION_ID),error=>error.message==='phase4b_upload_outcome_ambiguous_reconciliation_required_no_retry');assert.equal(requireUploadedVersionIdentity({id:'11111111-1111-4111-8111-111111111111'},EXPECTED_ACTIVE_VERSION_ID),'11111111-1111-4111-8111-111111111111');});
test('candidate identity ambiguity cannot enter postflight, retry or cleanup while known-candidate postflight remains quarantined',()=>{const extraction=helper.indexOf('uploadedId=requireUploadedVersionIdentity'),postflight=helper.indexOf('try{',extraction),blocked=helper.indexOf('phase4b_postflight_failed_candidate_quarantined_deployment_blocked');assert.ok(extraction>0&&postflight>extraction&&blocked>postflight);assert.equal((helper.match(/await submitVersionUpload\(\{/g)||[]).length,1);assert.doesNotMatch(helper,/deleteVersion|method:\s*'DELETE'|retry.*submitVersionUpload/i);});
test('successful summary describes latest pre-check and resolved bindings without exact-source overclaim',()=>{const summary=helper.slice(helper.indexOf('const summary=['));assert.doesNotMatch(summary,/inherited from exact active version|atomically pinned|guaranteed exact-source/i);assert.match(summary,/TEAMSHEET_DATA_DB` inherited via `latest` after expected-active pre-check; resolved D1 identity verified/);assert.match(summary,/DATA_S1_HTTP_AUTH_TOKEN` inherited via `latest` after expected-active pre-check; secret binding shape verified; value never read/);});
test('Cron and D1 are immutable pre/post invariants',()=>{assert.match(helper,/validateExactCron\(schedulesBefore\)/);assert.match(helper,/validateExactCron\(schedulesAfter\)/);assert.match(helper,/phase4b_d1_size_changed/);assert.match(helper,/validatePostPhase1State\(await readPhase1State\(\)\)/);});
test('manual workflow gates identity and CI before protected credentials',()=>{
  for(const expected of [/workflow_dispatch:/,/approved_sha:/,/refs\/heads\/main/,/priteshpatel390-del\/FPL/,/\^\[0-9a-f\]\{40\}\$/,/ref: \$\{\{ inputs\.approved_sha \}\}/,/ref: \$\{\{ needs\.repository-gate\.outputs\.approved_sha \}\}/,/git ls-remote/,/git status --porcelain/,/Tests and deterministic build/,/environment:\s*\n\s+name: data-s2b-phase3-deployment/,/node-version: 24\.19\.0/,/needs: repository-gate/])assert.match(workflow,expected);
  assert.doesNotMatch(workflow,/^\s{2}(?:push|schedule|pull_request|pull_request_target|workflow_run|repository_dispatch|issue_comment):/m);
  for(const credential of ['CLOUDFLARE_WORKER_UPLOAD_TOKEN','CLOUDFLARE_PHASE3_DEPLOY_TOKEN','CLOUDFLARE_ACCOUNT_ID','DATA_S1_HTTP_AUTH_TOKEN','CF_ACCESS_CLIENT_ID','CF_ACCESS_CLIENT_SECRET','data-s2b-phase3-deployment'])assert.ok(workflow.indexOf('repository-gate:')<workflow.indexOf(credential));
});
test('workflow maps the proven Phase 3 protected environment credentials exactly',()=>{
  assert.match(workflow,/CLOUDFLARE_WORKER_UPLOAD_TOKEN: \$\{\{ secrets\.CLOUDFLARE_PHASE3_DEPLOY_TOKEN \}\}/);
  for(const retained of [/CLOUDFLARE_ACCOUNT_ID: \$\{\{ secrets\.CLOUDFLARE_ACCOUNT_ID \}\}/,/DATA_S1_HTTP_AUTH_TOKEN: \$\{\{ secrets\.DATA_S1_HTTP_AUTH_TOKEN \}\}/,/CF_ACCESS_CLIENT_ID: \$\{\{ secrets\.CF_ACCESS_CLIENT_ID \}\}/,/CF_ACCESS_CLIENT_SECRET: \$\{\{ secrets\.CF_ACCESS_CLIENT_SECRET \}\}/])assert.match(workflow,retained);
  assert.deepEqual([...new Set([...workflow.matchAll(/secrets\.([A-Z0-9_]+)/g)].map(row=>row[1]))].sort(),['CF_ACCESS_CLIENT_ID','CF_ACCESS_CLIENT_SECRET','CLOUDFLARE_ACCOUNT_ID','CLOUDFLARE_PHASE3_DEPLOY_TOKEN','DATA_S1_HTTP_AUTH_TOKEN']);
  assert.doesNotMatch(workflow,/secrets\.CLOUDFLARE_WORKER_UPLOAD_TOKEN|secrets\.CLOUDFLARE_API_TOKEN|CLOUDFLARE_D1_WRITE_TOKEN|data-s2b-phase(?:0-readonly|1-migration|2-version-upload)/);
});
test('workflow invokes only the standalone upload executable and no deployment, preflight, migration or collector path',()=>{
  assert.deepEqual([...workflow.matchAll(/node\s+(\S+\.mjs)/g)].map(row=>row[1]),['workers/data-platform/phase4b/upload-version.mjs']);
  assert.doesNotMatch(workflow,/deploy-version\.mjs|preflight\.mjs|deploy-candidate\.mjs|migrate-0002\.mjs|readonly-closeout\.mjs|collector\.mjs|wrangler\s+(?:deploy|triggers(?:\s+deploy)?)/);
});
