import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';
import {FUTURE_PRODUCTION_COLLECTION_SCHEDULE,MAX_D1_API_CALLS_PER_CYCLE,MAX_D1_ROWS_READ_PER_CYCLE,MAX_D1_ROWS_WRITTEN_PER_CYCLE,OFFICIAL_FPL_ENDPOINTS,PRODUCTION_D1_ID,runProductionCollection} from '../workers/data-platform/production-collection.mjs';
const account='production_account';const fingerprint=createHash('sha256').update(account).digest('hex');
const revision={migration_version:2,migration_name:'official_fpl_structured_history',source_revision_id:'official-fpl-r1',source_id:'source-official-fpl',revision:1,schema_version:'data-s2a-v1',rights_classification:'durable_allowed',retention_allowed:1,redistribution_allowed:0,attribution_required:0,attribution_text:null,terms_reference:'docs/DATA_SOURCES.md',terms_reviewed_at:'2026-08-26T00:00:00.000Z',acquisition_status:'approved_internal_shadow_history',shadow_ingest_allowed:1,supersedes_revision_id:null,created_at:'2026-08-26T00:00:00.000Z',source_key:'official-fpl',source_kind:'official_fpl'};
function world(){const events=Array.from({length:38},(_,i)=>({id:i+1,name:`GW ${i+1}`,deadline_time:new Date(Date.UTC(2026,7,15+i*7)).toISOString()}));const teams=Array.from({length:20},(_,i)=>({id:i+1,name:`Team ${i+1}`,short_name:`T${i+1}`,strength:1,strength_overall_home:1,strength_overall_away:1,strength_attack_home:1,strength_attack_away:1,strength_defence_home:1,strength_defence_away:1}));const elements=Array.from({length:400},(_,i)=>({id:i+1,team:i%20+1,element_type:i%4+1,web_name:`P${i}`,now_cost:50,status:'a',chance_of_playing_next_round:null,chance_of_playing_this_round:null,news:'',news_added:null,selected_by_percent:'1'}));const fixtures=Array.from({length:300},(_,i)=>({id:i+1,event:i%38+1,kickoff_time:new Date(Date.UTC(2026,8,1+i)).toISOString(),team_h:i%20+1,team_a:(i+1)%20+1,team_h_difficulty:2,team_a_difficulty:2}));return [{events,teams,elements,element_types:[{id:1},{id:2},{id:3},{id:4}]},fixtures];}
const response=value=>({status:200,arrayBuffer:async()=>new TextEncoder().encode(JSON.stringify(value)).buffer});
function harness({heads=[],ambiguousCommit=false}={}){const requests=[];let run=null;const transport=async request=>{requests.push(request);const body=JSON.parse(request.body),statements=body.batch??[body],sql=statements[0].sql;if(sql.includes('schema_migrations'))return ok([[revision]],1,0);if(sql.startsWith('SELECT run_id'))return ok([[...(run?[run]:[])]],1,0);if(sql.startsWith('SELECT o.*'))return ok([heads],heads.length,0);if(sql.startsWith('INSERT OR IGNORE INTO ingestion_runs')){run={status:'started',records_accepted:0,records_seen:0};return ok([[]],0,1);}if(sql.startsWith('UPDATE ingestion_runs')||statements.at(-1).sql.startsWith('UPDATE ingestion_runs')){const accepted=Number(statements.at(-1).params[2]);run={status:'completed',records_accepted:accepted,records_seen:Number(statements.at(-1).params[1])};if(ambiguousCommit)throw new Error('lost response');return ok(statements.map(()=>[]),0,accepted*2+1);}throw new Error('unexpected');};return {requests,transport};}
function ok(results,read,written){return {status:200,json:async()=>({success:true,result:results.map((rows,i)=>({success:true,results:rows,meta:{rows_read:i?0:read,rows_written:i?0:written,changes:0}}))})};}
const options=transport=>({accountId:account,accountFingerprint:fingerprint,databaseId:PRODUCTION_D1_ID,season:'2026-27',token:'secret',scheduledAt:'2026-09-02T01:17:00.000Z',transport,fetchImpl:async url=>response(world()[OFFICIAL_FPL_ENDPOINTS.indexOf(url)])});

test('initial activation is manual-only: PR, push and schedule cannot trigger collection',()=>{const yml=fs.readFileSync('.github/workflows/data-s2-production-collection.yml','utf8');const trigger=yml.slice(yml.indexOf('on:'),yml.indexOf('\npermissions:'));assert.match(trigger,/^on:\s+workflow_dispatch:\s*$/m);assert.doesNotMatch(trigger,/pull_request:|push:|schedule:|cron:/);assert.match(yml,/if: github\.event_name == 'workflow_dispatch'/);assert.doesNotMatch(yml,/github\.event_name == '(?:schedule|push|pull_request)'/);assert.equal(FUTURE_PRODUCTION_COLLECTION_SCHEDULE,'17 1 * * *');});
test('manual workflow retains protected environment, main checkout, least privilege and serialization',()=>{const yml=fs.readFileSync('.github/workflows/data-s2-production-collection.yml','utf8');assert.match(yml,/permissions:\s+contents: read/);assert.match(yml,/environment:\s+name: data-s2-production-collection/);assert.match(yml,/group: data-s2-production-collection\s+cancel-in-progress: false/);assert.match(yml,/ref: main/);assert.doesNotMatch(yml,/workers\/scripts|schedules|wrangler/);});
test('fixed endpoints, identities, season and budgets are closed constants',()=>{assert.deepEqual([...OFFICIAL_FPL_ENDPOINTS],['https://fantasy.premierleague.com/api/bootstrap-static/','https://fantasy.premierleague.com/api/fixtures/']);assert.equal(PRODUCTION_D1_ID,'01e2b4f9-313a-4a14-8ce6-86c5aecc50d7');assert.ok(MAX_D1_API_CALLS_PER_CYCLE<=8&&MAX_D1_ROWS_READ_PER_CYCLE<=25000&&MAX_D1_ROWS_WRITTEN_PER_CYCLE<=40000);});
test('unchanged collection writes bookkeeping only and leaves observation/head writes absent',async()=>{const first=world();const {normaliseOfficialFplHistory}=await import('../workers/data-platform/official-fpl-canonical.mjs');const heads=normaliseOfficialFplHistory({bootstrap:first[0],fixtures:first[1],season:'2026-27',fetchedAt:'2026-09-02T01:17:00.000Z'}).candidates.map(row=>({...row,value_boolean:row.value_type==='boolean'?Number(row.value_boolean):row.value_boolean}));const h=harness({heads});const result=await runProductionCollection(options(h.transport));assert.equal(result.result,'unchanged');assert.equal(result.changed,0);assert.equal(h.requests.filter(r=>r.body.includes('INSERT INTO shadow_observations')).length,0);assert.equal(h.requests.filter(r=>r.body.includes('observation_heads (')).length,0);});
test('changed collection is bounded and ambiguous commit reconciles without retry',async()=>{const h=harness({ambiguousCommit:true});const result=await runProductionCollection(options(h.transport));assert.equal(result.result,'changed_reconciled');assert.ok(result.changed>0&&result.changed<15000);assert.equal(h.requests.filter(r=>r.body.includes('INSERT INTO shadow_observations')).length,1);});
test('wrong fingerprint, D1 and season fail before dispatch without credential output',async()=>{const h=harness();for(const changed of [{accountFingerprint:'0'.repeat(64)},{databaseId:'wrong'},{season:'2025-26'}])await assert.rejects(runProductionCollection({...options(h.transport),...changed}),error=>{assert.doesNotMatch(String(error),/secret|production_account$/);return true;});assert.equal(h.requests.length,0);});
