import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {canonicalFplId,replayAt,rightsAdmission,safetyReason,validateMapping,validateObservation} from '../workers/data-platform/data-platform-core.mjs';
import worker from '../workers/data-platform/data-platform.mjs';

const revision=(rights='durable_allowed',extra={})=>({rights_classification:rights,retention_allowed:1,shadow_ingest_allowed:1,...extra});
const observation=(extra={})=>({observation_id:'o1',logical_key:'availability:p1',ingestion_run_id:'run1',source_revision_id:'rev1',category:'availability',subject_type:'player',subject_entity_id:'2026-27:fpl:player:351',metric:'available',value_type:'boolean',value_boolean:1,observed_at:'2026-08-20T10:00:00Z',effective_at:'2026-08-20T10:00:00Z',fetched_at:'2026-08-20T10:01:00Z',transform_version:'1',validation_version:'1',input_revision:'r1',mode:'shadow_only',...extra});

test('migration creates the isolated ten-table foundation with hard shadow constraints',()=>{const sql=fs.readFileSync('workers/data-platform/migrations/0001_shadow_data_foundation.sql','utf8');for(const table of ['schema_migrations','data_sources','data_source_revisions','ingestion_runs','canonical_entities','entity_mappings','shadow_observations','observation_relations','observation_heads','observation_rejections'])assert.match(sql,new RegExp(`CREATE TABLE ${table}`));assert.match(sql,/CHECK\(mode='shadow_only'\)/g);assert.doesNotMatch(sql,/EVIDENCE_DB|R2|production_eligible/);});
test('wrangler is a new D1-only private service with no route, R2, cron or browser config',()=>{const text=fs.readFileSync('workers/data-platform/wrangler.jsonc','utf8');assert.match(text,/teamsheet-data-platform/);assert.match(text,/TEAMSHEET_DATA_DB/);assert.match(text,/teamsheet-data/);assert.doesNotMatch(text,/EVIDENCE_DB|r2_buckets|routes|triggers|cors/i);});
test('rights durable admission is fail closed',()=>{assert.equal(rightsAdmission(revision()).ok,true);assert.equal(rightsAdmission(revision('attribution_required',{attribution_text:'Source attribution'})).ok,true);assert.equal(rightsAdmission(revision('attribution_required')).reason,'attribution_missing');assert.equal(rightsAdmission(revision('local_research_only')).reason,'local_research_only');assert.equal(rightsAdmission(revision('durable_blocked')).reason,'durable_storage_blocked');assert.equal(rightsAdmission(revision('unknown_fail_closed')).reason,'rights_unknown');assert.equal(rightsAdmission({rights_classification:'new_right'}).reason,'rights_unknown');});
test('recursive secret and credential URL guard rejects representative forbidden material',()=>{for(const key of ['apiKey','api_token','token','secret','Authorization','Cf-Access-Jwt-Assertion','Cookie','OPENAI_API_KEY','ANTHROPIC_API_KEY'])assert.equal(safetyReason({nested:[{[key]:'x'}]}),'secret_detected',key);for(const value of ['Bearer abcdef','https://x.test/a?key=x','https://x.test/a?token=x','https://x.test/a?api_key=x','https://user:pass@x.test/a'])assert.ok(safetyReason({nested:[value]}),value);});
test('observation contract permits only one typed scalar and shadow_only',()=>{assert.equal(validateObservation(observation(),revision()).ok,true);assert.equal(validateObservation(observation({mode:'production_eligible'}),revision()).reason,'mode_invalid');assert.equal(validateObservation(observation({value_text:'also'}),revision()).reason,'value_invalid');assert.equal(validateObservation(observation({fetched_at:'bad'}),revision()).reason,'value_invalid');});
test('canonical FPL identities are stable and season scoped',()=>{assert.equal(canonicalFplId({season:'2026-27',type:'player',id:351}),'2026-27:fpl:player:351');assert.notEqual(canonicalFplId({season:'2025-26',type:'player',id:351}),canonicalFplId({season:'2026-27',type:'player',id:351}));});
test('only stable-ID mapping methods verify; name-only, unresolved and ambiguous mappings fail',()=>{assert.equal(validateMapping({provider_entity_id:'provider-9',mapping_method:'provider_id_crosswalk',mapping_status:'verified'}).ok,true);assert.equal(validateMapping({provider_entity_id:'provider-9',mapping_method:'display_name',mapping_status:'verified'}).reason,'mapping_unresolved');assert.equal(validateMapping({provider_entity_id:'provider-9',mapping_method:'manually_verified',mapping_status:'ambiguous'}).reason,'mapping_ambiguous');});
test('mapping and observation schema preserve superseded history and conflicts',()=>{const sql=fs.readFileSync('workers/data-platform/migrations/0001_shadow_data_foundation.sql','utf8');assert.match(sql,/supersedes_mapping_id TEXT REFERENCES entity_mappings/);assert.match(sql,/conflicts_with/);assert.match(sql,/shadow_observations\(source_revision_id, logical_key, input_revision\)/);assert.doesNotMatch(sql,/UPDATE shadow_observations|DELETE FROM shadow_observations/);});
test('point-in-time replay excludes later corrections and preserves stale/conflicting history',()=>{const old=observation({observation_id:'old',fetched_at:'2026-08-20T10:00:00Z',quality_state:'stale'});const correction=observation({observation_id:'new',input_revision:'r2',fetched_at:'2026-08-20T12:00:00Z',quality_state:'conflicting'});assert.deepEqual(replayAt([correction,old],'2026-08-20T11:00:00Z').map(x=>x.observation_id),['old']);assert.deepEqual(replayAt([correction,old],'2026-08-20T13:00:00Z').map(x=>x.observation_id),['old','new']);});
test('worker health is narrow and exposes no CORS',async()=>{const response=await worker.fetch(new Request('https://internal/v1/health'),{});assert.equal(response.status,200);assert.equal(response.headers.get('access-control-allow-origin'),null);assert.deepEqual(await response.json(),{ok:true,platformVersion:'1.0.0',mode:'shadow_only'});});
test('D1 read/write failures are redacted and isolated',async()=>{const failing={prepare(){throw new Error('Bearer live-secret https://key.test/?api_key=x');}};let response=await worker.fetch(new Request('https://internal/v1/shadow/observations?as_of=2026-08-20T10:00:00Z'),{TEAMSHEET_DATA_DB:failing});assert.equal(response.status,503);assert.deepEqual(await response.json(),{error:'storage_read_failed'});response=await worker.fetch(new Request('https://internal/v1/shadow/observations',{method:'POST',body:JSON.stringify(observation())}),{TEAMSHEET_DATA_DB:failing});assert.equal(response.status,503);assert.deepEqual(await response.json(),{error:'storage_read_failed'});});
test('production source has no dependency on DATA-S1 and approved provider state is unchanged',()=>{for(const file of fs.readdirSync('src').filter(x=>x.endsWith('.mjs'))){const text=fs.readFileSync(path.join('src',file),'utf8');assert.doesNotMatch(text,/data-platform|TEAMSHEET_DATA_DB|shadow_observations/);}const all=fs.readFileSync('workers/evidence-archive-core.mjs','utf8');assert.match(all,/APPROVED_PROVIDER_NAMES=Object\.freeze\(\['fpl','understat','odds','archive'\]\)/);});
test('shadow scenarios cannot mutate production files, CSP or provider/model state',()=>{const protectedFiles=['src/main.mjs','src/state.mjs','src/squad.mjs','app.html','workers/evidence-archive-core.mjs','workers/evidence-archive.mjs'];const before=protectedFiles.map(file=>fs.readFileSync(file));for(const scenario of [[],[observation()],[observation({quality_state:'stale'})],[observation({mode:'bad'})],[observation({conflict_group_id:'c1',quality_state:'conflicting'})]])replayAt(scenario.filter(x=>Number.isFinite(Date.parse(x.fetched_at))),'2099-01-01T00:00:00Z');protectedFiles.forEach((file,index)=>assert.deepEqual(fs.readFileSync(file),before[index]));assert.doesNotMatch(fs.readFileSync('app.html','utf8'),/teamsheet-data-platform|TEAMSHEET_DATA_DB/);});
test('C5 custody files remain byte-identical to authoritative main',()=>{for(const file of ['workers/evidence-archive-core.mjs','workers/evidence-archive.mjs','workers/evidence-wrangler.jsonc','workers/evidence-migrations/0001_evidence_foundation.sql','workers/fpl-gateway.mjs'])assert.deepEqual(fs.readFileSync(file),execFileSync('git',['show',`origin/main:${file}`]));});
