import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import * as plan from '../workers/data-platform/e2-d1-rest-validation-plan.mjs';
import {canonicalizeLiveSchema,deriveLiveSchemaFingerprint,validateInitialLiveObjects,validateSetupLiveSchema} from '../workers/data-platform/e2-live-schema-contract.mjs';
import {createE2LiveHttpAdapter,E2_LIVE_HTTP_CAPABILITY} from '../workers/data-platform/e2-live-http-adapter.mjs';
import {runE2LiveContract} from '../workers/data-platform/e2-live-orchestrator.mjs';

test('W00 is separate, exact and mandatory for a provable W01 completion',()=>{
  const w00=plan.buildFullWriteRunStart();assert.equal(w00.caseId,'W00');assert.equal(w00.statements.length,1);assert.deepEqual(w00.statements[0].params,['e2-run-full-write','0']);
  assert.equal(plan.reconcileFullWriteRunStart([{run_id:'e2-run-full-write',status:'started',records_accepted:0}]),true);
  assert.equal(plan.reconcileFullWriteRunStart([]),false);assert.equal(plan.reconcileFullWriteRunStart([{run_id:'e2-run-full-write',status:'completed',records_accepted:9860}]),false);
  const w01=plan.buildSyntheticFullWriteAnalogue();assert.equal(w01.statements.length,24);assert.equal(plan.serializedBodyBytes(w01),2378752);assert.doesNotMatch(w01.statements[0].sql,/e2_runs/);
});
test('W01 reconciliation requires all exact counts, referential integrity and one affected completion row',()=>{
 const row={entities:1064,observations:9860,heads:9860,orphan_heads:0,run_rows:1,run_status:'completed',records_accepted:9860};assert.equal(plan.reconcileFullWrite([row],1),true);assert.equal(plan.reconcileFullWrite([row],0),false);
 for(const key of Object.keys(row))assert.equal(plan.reconcileFullWrite([{...row,[key]:key==='run_status'?'started':999}],1),false);
});
test('affinity probes distinguish binding, conversion, equality, ordering, JSON and storage affinity',()=>{
 const affinity=plan.buildAffinityPlan(),raw=JSON.stringify(affinity);for(const value of ['42','3.125','0042','0','1','true','false'])assert.ok(affinity.statements.flatMap(x=>x.params).includes(value));
 for(const token of ['typeof(CAST','COLLATE BINARY','text_order','numeric_order','json_type','sqlite_value_type'])assert.match(raw,new RegExp(token.replace(/[()]/g,'\\$&')));
 assert.deepEqual(JSON.parse(affinity.statements.at(-1).params[0]).map(x=>x.value),[42,3.125,'0042',true,null]);assert.equal(plan.buildStorageAffinityMutation().mutation,true);assert.equal(plan.buildStorageAffinityReconciliation().mutation,false);
});
const schema=[{name:'e2_x',sql:'CREATE TABLE e2_x(a TEXT CHECK(a<>\'\'))',columns:[{cid:0,name:'a',type:'TEXT',notnull:1,dflt_value:null,pk:1}],indexes:[{name:'sqlite_autoindex_e2_x_1',unique:1,origin:'pk',columns:[{seqno:0,cid:0,name:'a',coll:'BINARY'}]}],foreignKeys:[]}];
test('live semantic schema identity is deterministic and drift-sensitive',()=>{assert.equal(canonicalizeLiveSchema(schema),canonicalizeLiveSchema(structuredClone(schema)));assert.equal(deriveLiveSchemaFingerprint(schema),deriveLiveSchemaFingerprint(structuredClone(schema)));for(const changed of [[{...schema[0],columns:[{...schema[0].columns[0],type:'INTEGER'}]}],[{...schema[0],sql:'CREATE TABLE e2_x(a TEXT)'}]])assert.notEqual(deriveLiveSchemaFingerprint(changed),deriveLiveSchemaFingerprint(schema));});
test('initial/setup schema policies are closed and production-safe',()=>{assert.equal(validateInitialLiveObjects([]),true);assert.equal(validateInitialLiveObjects([{type:'table',name:'sqlite_sequence'}]),true);for(const row of [{type:'table',name:'_cf_future'},{type:'view',name:'sqlite_sequence'},{type:'table',name:'shadow_observations'}])assert.throws(()=>validateInitialLiveObjects([row]));assert.throws(()=>validateSetupLiveSchema(schema),/tables_mismatch/);});
test('fixed HTTP adapter exposes only exact metadata GET and query POST',async()=>{const calls=[];const adapter=createE2LiveHttpAdapter({accountId:'acct_e2',databaseId:'12345678-1234-1234-1234-123456789abc',token:'secret',fetchImpl:async(...args)=>{calls.push(args);return {};}});assert.deepEqual(Object.keys(adapter),['readExactMetadata','query']);await adapter.readExactMetadata();await adapter.query('{}');assert.equal(calls[0][1].method,'GET');assert.equal(calls[1][1].method,'POST');assert.match(calls[1][0],/\/d1\/database\/12345678-1234-1234-1234-123456789abc\/query$/);assert.deepEqual(E2_LIVE_HTTP_CAPABILITY.queryMethod,'POST');assert.throws(()=>createE2LiveHttpAdapter({accountId:'x',databaseId:'teamsheet-data',token:'x',fetchImpl:()=>{}}));});

const identity={accountFingerprint:'acct-e2',approvedAccountFingerprint:'acct-e2',productionAccountFingerprint:'acct-production',databaseName:'teamsheet-data-e2-rest-validation-20260901-a1b2c3',databaseFingerprint:'db-e2',expectedDatabaseFingerprint:'db-e2',schemaFingerprint:plan.E2_INITIAL_SCHEMA_FINGERPRINT,tables:[]};
const goodReconcile=async p=>p.caseId==='SCHEMA-RECONCILE'?{accepted:true}:p.caseId?.startsWith('A04-')?{rows:p.caseId.endsWith('A01')?[{sequence_no:1},{sequence_no:2},{sequence_no:3}]:[]}:p.caseId==='P-STORAGE-READ'?{accepted:true}:p.caseId==='W00-R'?{rows:[{run_id:'e2-run-full-write',status:'started',records_accepted:0}]}:{rows:[{entities:1064,observations:9860,heads:9860,orphan_heads:0,run_rows:1,run_status:'completed',records_accepted:9860}]};
test('orchestration order is fixed, reaches 125%, and mutations dispatch once',async()=>{const seen=[];const result=await runE2LiveContract({sourceSha:'a'.repeat(40),approvedSourceSha:'a'.repeat(40),runnerIdentity:'runner-v1',identity,initialObjects:[],query:async p=>{seen.push(p.caseId);return {classification:'SUCCESS',completionChanges:p.caseId==='W01'?1:undefined};},reconcile:goodReconcile});assert.equal(result.state,'STOP');assert.deepEqual(seen.slice(-2),['W00','W01']);assert.equal(seen.filter(x=>x==='W01').length,1);assert.equal(seen.at(seen.indexOf('A01')-1),`L-body-${plan.E2_BODY_PROFILE_TARGETS.at(-1)}`);for(const id of ['A01','A02','A03','P-STORAGE-WRITE','W00','W01'])assert.equal(result.dispatchCounts[id],1);assert.ok(result.evidence.every(x=>x.cleanupState==='NOT_PERFORMED_BY_E2C_A'&&!JSON.stringify(x).includes('secret')));});
test('failed body gate stops before mutations and ambiguous mutation is never retried',async()=>{const seen=[];await assert.rejects(runE2LiveContract({sourceSha:'b'.repeat(40),approvedSourceSha:'b'.repeat(40),runnerIdentity:'runner-v1',identity,initialObjects:[],query:async p=>{seen.push(p.caseId);return {classification:p.caseId===`L-body-${plan.E2_BODY_PROFILE_TARGETS[3]}`?'FAILED':'SUCCESS'};},reconcile:goodReconcile}),/e2_body_profile_failed/);assert.ok(!seen.includes('A01'));const seen2=[];await assert.rejects(runE2LiveContract({sourceSha:'c'.repeat(40),approvedSourceSha:'c'.repeat(40),runnerIdentity:'runner-v1',identity,initialObjects:[],query:async p=>{seen2.push(p.caseId);if(p.caseId==='A01')throw new Error('timeout');return {classification:'SUCCESS'};},reconcile:goodReconcile}),/e2_a01/);assert.equal(seen2.filter(x=>x==='A01').length,1);});
test('identity firewall and static authority surface fail closed',async()=>{await assert.rejects(runE2LiveContract({sourceSha:'d'.repeat(40),approvedSourceSha:'e'.repeat(40),runnerIdentity:'x',identity,initialObjects:[],query:async()=>{},reconcile:async()=>{}}),/source_sha/);for(const bad of [{...identity,accountFingerprint:'acct-production',approvedAccountFingerprint:'acct-production'},{...identity,databaseName:'teamsheet-data'},{...identity,databaseFingerprint:'wrong'}])await assert.rejects(runE2LiveContract({sourceSha:'d'.repeat(40),approvedSourceSha:'d'.repeat(40),runnerIdentity:'x',identity:bad,initialObjects:[],query:async()=>{},reconcile:async()=>{}}));const files=['workers/data-platform/e2-live-http-adapter.mjs','workers/data-platform/e2-live-orchestrator.mjs'];const raw=files.map(f=>fs.readFileSync(f,'utf8')).join('\n');for(const forbidden of ['wrangler deploy','set -x','/workers/scripts','/access/','/secrets','/zones','/routes','database/create','database/delete','console.log','process.env'])assert.doesNotMatch(raw,new RegExp(forbidden.replace('/','\\/'),'i'));});
