import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {adaptPreDeadlineSnapshot,adaptOfficialOutcome,adaptDataS2bOfficialFpl} from '../src/decision-intelligence/eia1-evidence-adapters.mjs';
import {normaliseWorkloadObservation,workloadExperimentArms} from '../src/decision-intelligence/eia1-workload-contract.mjs';
import {buildCapabilityReport} from '../scripts/thesportsdb-eia1-probe.mjs';
import {finaliseSnapshotRecord} from '../src/evidence/snapshot.mjs';
import {finaliseOutcomeRecord} from '../src/evidence/outcome.mjs';
import {DI3_PARITY_POLICY} from '../src/decision-intelligence/parity-integration.mjs';

const deadline='2026-09-01T17:30:00.000Z',cutoff='2026-09-01T17:00:00.000Z';
const managerRef='mgr-0123456789abcdef0123456789abcdef';
const completed=Date.parse('2026-09-01T16:59:00.000Z');
const network=at=>({status:'available',serverAt:at,clientMidpointAt:at,skewMs:0,requestStartedAt:at-20,responseReceivedAt:at+20,roundTripMs:40,source:'same_origin_http_date'});
const providers=()=>['fpl','understat','odds','archive'].map(name=>({provider:name,state:name==='fpl'?'Live':'Disabled',included:name==='fpl',didAffectModel:name==='fpl',acceptedRecordCount:name==='fpl'?1:0,rejectedRecordCount:0,lastSuccessAt:name==='fpl'?new Date(completed-1000).toISOString():null,recordedAt:new Date(completed-1000).toISOString(),ageMs:name==='fpl'?0:null,thresholdMs:null,note:'',consequence:''}));
function snapshotPayload(){return {recordType:'preDeadlineSnapshot',schemaVersion:'1.0.0',metricVersion:'1.0.0',segmentationVersion:'1.0.0',managerRef,season:'2026-27',gameweek:2,deadlineTime:deadline,capture:{startedAt:new Date(completed-2000).toISOString(),projectionStartedAt:new Date(completed-1500).toISOString(),projectionCompletedAt:new Date(completed).toISOString(),horizon:6},build:{modelVersion:'2.4.0',rulesVersion:'2026-27.3',sourceHash:'source',commit:'source',moduleOrder:[]},versions:{model:'2.4.0',rules:'2026-27.3',simulation:'1.0.0',snapshot:'1.0.0'},rules:{fpl:{season:'2026-27'},minutes:{version:'1'},scoring:{},transfer:{},simulation:{version:'1.0.0'},odds:{},fixture:{baseGoals:1.42,homeTilt:1.1}},providers:providers(),retries:[],issues:[],modelInputs:{events:[],teams:[],players:[{id:2,status:'a'}],fixtures:[],minuteHistory:{2:[{event:1,minutes:90}]},calibration:null,understat:null,odds:null},outputs:{players:[{playerId:2,minutes:{minutes:74,pStart:.8,pAppear:.9,p60:.7},nextGameweek:{gw:2,total:4,games:1,parts:{}},perGameweek:[],aggregate:{fromGameweek:2,horizon:6,total:20,perGameweek:[],games:6,parts:{}},uncertainty:{status:'available'},sourceUsage:{fpl:true}}],squad:{status:'not_available'}},completeness:{complete:true,sections:{coreInputs:'complete',playerProjections:'complete'},fatalFplIssue:false,playerCount:1,expectedPlayerCount:1},quality:{projectionDurationMs:500,simulationSamplesPerAvailablePlayer:5000,seasonLive:true}};}
async function canonicalSnapshot(){return finaliseSnapshotRecord(snapshotPayload(),{captureStartedAt:completed-2000,captureCompletedAt:completed,networkBefore:network(completed-1900),networkAfter:network(completed)});}
function outcomePayload(snapshot,{minutes=63,starts=1,status='complete'}={}){const appeared=minutes>0,reachedSixty=minutes>=60;return {recordType:'gameweekOutcome',schemaVersion:'1.0.0',managerRef,season:'2026-27',gameweek:2,status,collection:{startedAt:'2026-09-02T18:00:00.000Z',completedAt:'2026-09-02T18:01:00.000Z',finalisedAt:status==='provisional'?null:'2026-09-02T18:01:00.000Z',trigger:'automatic',mode:'prospective_recheck',origin:'local_collection'},build:{commit:'source'},versions:{outcome:'1.0.0',snapshot:'1.0.0',model:'2.4.0',rules:'2026-27.3',simulation:'1.0.0'},officialDeadlineIdentity:{eventId:2,deadlineTime:deadline,eventFinished:true,dataChecked:status!=='provisional',fixtureAssignmentHash:'a'.repeat(64)},sourceProvenance:{provider:'fpl',authority:'official',endpoints:[{endpoint:'/event/{gw}/live/',fetchedAt:'2026-09-02T18:01:00.000Z',normalisedHash:'b'.repeat(64)}],retrySummary:[]},relatedSnapshot:{status:'matched_official',snapshotId:snapshot.identity.snapshotId,contentHash:snapshot.identity.contentHash,deadlineTime:deadline,timingGrade:snapshot.timing.grade,buildCommit:'source',modelVersion:'2.4.0',rulesVersion:'2026-27.3'},fixtureOutcomes:{status:status==='provisional'?'provisional':'complete',records:[{fixtureId:10,event:2,homeTeamId:1,awayTeamId:2,finished:status!=='provisional'}]},allPlayerOutcomes:{status:'complete',records:[{playerId:2,totalPoints:6,minutes,starts,appeared,reachedSixty,perFixture:[]}]},realSquadOutcome:{status:'not_available',reason:'public_manager_outcome_unavailable',picks:[]},completeness:{complete:status!=='provisional',sections:{event:status==='provisional'?'provisional':'complete',fixtures:status==='provisional'?'provisional':'complete',players:'complete',squad:'not_available'},fixtureCount:1,finishedFixtureCount:status==='provisional'?0:1,playerCount:1,expectedPlayerCount:1,duplicateFixtureCount:0,duplicatePlayerCount:0},validation:{disposition:status==='provisional'?'provisional_acceptance':'accepted',issues:[]},identity:{logicalKey:'2026-27|gw2',revision:null,rootOutcomeId:null,supersedesOutcomeId:null,outcomeDataHash:null,sectionHashes:null,contentHash:null,outcomeId:null}};}
async function canonicalOutcome(snapshot,options={},previousRecord=null){return (await finaliseOutcomeRecord(outcomePayload(snapshot,options),{previousRecord})).record;}
const observation=(overrides={})=>({observation_id:'obs-1',logical_key:'official-fpl|2026-27|player|2|status',ingestion_run_id:'run',source_revision_id:'official-fpl-r1',category:'official_fpl_player',subject_type:'player',subject_entity_id:'2026-27:fpl:player:2',metric:'status',value_type:'text',value_text:'a',observed_at:null,effective_at:null,fetched_at:'2026-09-01T16:00:00.000Z',expires_at:null,source_timestamp:null,transform_version:'data-s2a-official-fpl-history-v1',validation_version:'data-s2a-official-fpl-validation-v2',input_revision:'run',admission_state:'accepted',quality_state:'fresh',mode:'shadow_only',provenance_kind:'canonical_native_fpl',...overrides});
const dataExport=(pages,asOf=cutoff)=>({schemaVersion:'eia1-data-s2b-export-v1',as_of:asOf,pages});
const page=(observations,{requestCursor=null,nextCursor=null,asOf=cutoff}={})=>({as_of:asOf,request_cursor:requestCursor,observations,next_cursor:nextCursor});

test('canonical snapshot is accepted and cutoff timestamps remain fail closed',async()=>{const snapshot=await canonicalSnapshot();assert.equal((await adaptPreDeadlineSnapshot(snapshot,{cutoff})).players[0].prediction.expectedMinutes,74);await assert.rejects(adaptPreDeadlineSnapshot(snapshot,{}),/cutoff_required/);await assert.rejects(adaptPreDeadlineSnapshot(snapshot,{cutoff:'2026-09-01T18:00:00Z'}),/cutoff_after_deadline/);});
test('snapshot integrity rejects post-finalisation xMins and baseline mutations',async()=>{const snapshot=await canonicalSnapshot();for(const mutate of [row=>{row.outputs.players[0].minutes.minutes=12;},row=>{row.outputs.players[0].minutes.pStart=.01;},row=>{row.modelInputs.players[0].status='u';},row=>{row.providers[0].acceptedRecordCount=99;}]){const tampered=structuredClone(snapshot);mutate(tampered);await assert.rejects(adaptPreDeadlineSnapshot(tampered,{cutoff}),/snapshot_integrity_/);}});
test('snapshot integrity rejects syntactically valid forged metadata',async()=>{const snapshot=structuredClone(await canonicalSnapshot());snapshot.identity.contentHash='f'.repeat(64);snapshot.identity.snapshotId='predeadline-gw2-ffffffffffffffff';await assert.rejects(adaptPreDeadlineSnapshot(snapshot,{cutoff}),/snapshot_integrity_/);});
test('canonical finalized and corrected outcomes are accepted',async()=>{const snapshot=await canonicalSnapshot(),input=await adaptPreDeadlineSnapshot(snapshot,{cutoff}),first=await canonicalOutcome(snapshot),corrected=await canonicalOutcome(snapshot,{minutes:64},first);assert.equal((await adaptOfficialOutcome(first,{snapshotInput:input})).players[0].targets.minutes,63);const adapted=await adaptOfficialOutcome(corrected,{snapshotInput:input});assert.equal(adapted.state.status,'corrected');assert.equal(adapted.state.supersedesOutcomeId,first.identity.outcomeId);});
test('outcome integrity rejects post-finalisation target, provenance and completeness mutations',async()=>{const snapshot=await canonicalSnapshot(),input=await adaptPreDeadlineSnapshot(snapshot,{cutoff}),outcome=await canonicalOutcome(snapshot);for(const mutate of [row=>{row.allPlayerOutcomes.records[0].minutes=1;},row=>{row.allPlayerOutcomes.records[0].starts=0;},row=>{row.allPlayerOutcomes.records[0].reachedSixty=false;},row=>{row.sourceProvenance.authority='secondary';},row=>{row.completeness.complete=false;}]){const tampered=structuredClone(outcome);mutate(tampered);await assert.rejects(adaptOfficialOutcome(tampered,{snapshotInput:input}),/outcome_integrity_/);}});
test('outcome integrity rejects syntactically self-consistent forged metadata',async()=>{const snapshot=await canonicalSnapshot(),input=await adaptPreDeadlineSnapshot(snapshot,{cutoff}),outcome=structuredClone(await canonicalOutcome(snapshot));outcome.identity.contentHash='f'.repeat(64);outcome.identity.outcomeId='outcome-2026-27-gw2-r1-ffffffffffffffff';await assert.rejects(adaptOfficialOutcome(outcome,{snapshotInput:input}),/outcome_integrity_/);});
test('DATA-S2B adapter proves and hash-binds a complete deterministic page chain while preserving real collector provenance',async()=>{const later=observation({observation_id:'obs-2',fetched_at:'2026-09-01T16:30:00Z'}),value=await adaptDataS2bOfficialFpl(dataExport([page([observation()],{nextCursor:'cursor-1'}),page([later],{requestCursor:'cursor-1'})]),{asOf:cutoff,deadlineTime:deadline});assert.deepEqual(value.pagination,[{page:1,requestCursor:null,nextCursor:'cursor-1',observationCount:1},{page:2,requestCursor:'cursor-1',nextCursor:null,observationCount:1}]);assert.equal(value.observations[0].transform_version,'data-s2a-official-fpl-history-v1');assert.equal(value.observations[0].validation_version,'data-s2a-official-fpl-validation-v2');const other=await adaptDataS2bOfficialFpl(dataExport([page([observation()],{nextCursor:'other'}),page([later],{requestCursor:'other'})]),{asOf:cutoff,deadlineTime:deadline});assert.notEqual(value.adapterHash,other.adapterHash);});
test('DATA-S2B adapter rejects incomplete, discontinuous, mixed, duplicate or unordered pagination',async()=>{const first=observation(),second=observation({observation_id:'obs-2',fetched_at:'2026-09-01T16:30:00Z'});for(const envelope of [dataExport([page([first],{nextCursor:'cursor-1'})]),dataExport([page([first],{nextCursor:'cursor-1'}),page([second],{requestCursor:'wrong'})]),dataExport([page([first]),page([second],{asOf:'2026-09-01T16:00:00Z'})]),dataExport([page([first,first])]),dataExport([page([second,first])])])await assert.rejects(adaptDataS2bOfficialFpl(envelope,{asOf:cutoff,deadlineTime:deadline}),/unterminated|cursor_chain|as_of|duplicate|order/);});
test('DATA-S2B adapter rejects malformed/leaking timestamps, unsupported facts and account data',async()=>{for(const fetched_at of [undefined,'malformed','2026-09-01T17:01:00Z'])await assert.rejects(adaptDataS2bOfficialFpl(dataExport([page([observation({fetched_at})])]),{asOf:cutoff,deadlineTime:deadline}),/fetched_at|post_cutoff/);await assert.rejects(adaptDataS2bOfficialFpl(dataExport([page([observation({metric:'minutes'})])]),{asOf:cutoff,deadlineTime:deadline}),/unsupported_fact/);await assert.rejects(adaptDataS2bOfficialFpl(dataExport([page([observation({manager_id:99})])]),{asOf:cutoff,deadlineTime:deadline}),/account_data/);});
const workload=()=>({schemaVersion:'eia1-workload-observation-v1',player:{canonicalId:'2026-27:fpl:player:2',mappingStatus:'verified'},team:{canonicalId:'2026-27:fpl:team:1'},competition:{providerId:'4480',type:'continental_cup'},fixture:{providerId:'event',scheduledKickoff:'2026-08-28T19:00:00Z',actualKickoff:null,venue:'away'},participation:{status:'starter',starter:true,minutes:null,substitutionOnMinute:null,substitutionOffMinute:null,extraTime:null},scheduleDensity:{previousFixture:null,nextFixture:null,restIntervalHours:null,matchesPrior7:null,matchesPrior14:null,matchesNext7:null,matchesNext14:null},playerWorkload:{nonPlStartsPrior7:null,nonPlStartsPrior14:null,nonPlMinutesPrior7:null,nonPlMinutesPrior14:null},timing:{sourceTimestamp:null,observedAt:'2026-08-29T00:00:00Z',fetchedAt:'2026-08-29T00:00:01Z'},correction:{status:'unknown',supersedes:null},quality:{state:'incomplete',missingFields:['minutes','extraTime']},provenance:{provider:'TheSportsDB',endpointClass:'official_api'},rights:{classification:'local_research_only',retention:'aggregate_metadata_only'}});
test('workload missingness and recursive secret protections remain fail closed',async()=>{const row=await normaliseWorkloadObservation(workload());assert.equal(row.participation.minutes,null);for(const provenance of [{nested:{apiKey:'not-real'}},{nested:{apiToken:'not-real'}},{nested:{authorization:'Bearer example'}},{url:'https://example.test/data?token=example'}])await assert.rejects(normaliseWorkloadObservation({...workload(),provenance}),/secret_material/);assert.equal(workloadExperimentArms().length,4);});
test('TheSportsDB report recursively blocks secrets, keyed URLs and raw payloads',async()=>{const safe={sample:{id:'fixed-v1',eventsRequested:4},rights:{classification:'local_research_only'},coverage:{lineupAvailable:0},reliability:{requests:4},qualification:'FAIL'};assert.match(await buildCapabilityReport(safe),/"durableRetention":"blocked"/);for(const bad of [{...safe,nested:{apiToken:'not-real'}},{...safe,nested:{url:'https://example.test/feed?key=example'}},{...safe,nested:{rawResponses:[{}]}},{...safe,nested:{payload:{events:[{id:'example'}]}}},{...safe,nested:{lineups:[{starter:true}]}}])await assert.rejects(buildCapabilityReport(bad),/forbidden/);});
test('research boundary is absent from production graphs and DI-3 approval remains empty',()=>{assert.deepEqual(DI3_PARITY_POLICY.allowedProductionSignals,[]);for(const file of ['src/main.mjs','src/model/minutes.mjs','src/model/scoring.mjs','src/model/transfers.mjs','src/providers/registry.mjs','src/ui/team-decision-home.mjs','src/ui/transfer-optimiser-view.mjs','src/decision-intelligence/parity-integration.mjs'])assert.doesNotMatch(fs.readFileSync(file,'utf8'),/eia1-|thesportsdb/i,file);});
test('EIA-1 changes no DATA-S2B Worker/schema/Cron/Cloudflare asset',()=>{assert.doesNotMatch(String(process.env.EIA1_CHANGED_FILES||''),/workers\/data-platform|wrangler|migrations|cloudflare/i);});
